{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_parameters=array() show_link=true()}
{if and( $object.main_node_id|null|not, $show_link )}
    <a href={$object.main_node.url_alias|ezurl}>{$object.name|wash}</a>
{else}
    {$object.name|wash}
{/if}
{/default}