ggwebservices: ggWebservicesRequest Class Reference
ggWebservicesRequest Class Reference
Generic class used to wrap webservices requests.
Public Member Functions
__construct ($name='', $parameters=array())
addParameter ($name, $value)
This call should be reversed: addParameter($value, $name='') to better support protocols with positional params.
addParameters ($params)
contentType ()
decodeStream ($rawRequest)
Used by servers when decoding incoming requests from the http request received.
method ()
as in 'http verb'. This is not the method name of the request.
name ()
Returns the request name.
parameters ()
payload ()
Returns the request payload encoded according to its specific protocol (in HTTP terms, this is the message body).
requestHeaders ()
requestURI ($uri)
Returns the final URI that will be used by the client, based on its initial version (except the protocol://host:port part).
Protected Attributes
$ContentType = ''
$Name
$Parameters = array()
Contains the request parameters.
$Verb = ''
Detailed Description
Generic class used to wrap webservices requests.
Modeled after eZP Soap equivalent.
Author
G. Giunta
Copyright
(C) 2009-2013 G. Giunta
Definition at line 9 of file ggwebservicesrequest.php.
Constructor & Destructor Documentation
ggWebservicesRequest::__construct ($name = '', $parameters = array())
Todo:
check: is this used anywhere? if not, remove it!
Definition at line 12 of file ggwebservicesrequest.php.
Member Function Documentation
ggWebservicesRequest::addParameter ($name, $value)
This call should be reversed: addParameter($value, $name='') to better support protocols with positional params.
Alas we keep compatibility with the eZP soap request class.
Parameters
string $name
mixed $value
Definition at line 68 of file ggwebservicesrequest.php.
Referenced by addParameters().
ggWebservicesRequest::addParameters ($params)
Parameters
array $params
Definition at line 76 of file ggwebservicesrequest.php.
ggWebservicesRequest::contentType ()
Definition at line 95 of file ggwebservicesrequest.php.
ggWebservicesRequest::decodeStream ($rawRequest) abstract
Used by servers when decoding incoming requests from the http request received.
Should set the Parameters and all relevant internal members
Parameters
string $rawRequest
Returns
bool false if received data cannot be parsed into a valid request
Todo:
this call is too naive, as it discards both http headers and URL, which might be needed for eg. REST protocolsrequire_once('../../../../../svn/projects.ez.no/ggwebservices/trunk/extension/ggwebservices/classes/ggxmlrpcrequest.php'); We keep it like this for now for backward compat, but it might change later on...
ggWebservicesRequest::method ()
as in 'http verb'. This is not the method name of the request.
Definition at line 90 of file ggwebservicesrequest.php.
ggWebservicesRequest::name ()
Returns the request name.
Definition at line 56 of file ggwebservicesrequest.php.
Referenced by ggSOAPRequest\requestHeaders().
ggWebservicesRequest::parameters ()
Definition at line 84 of file ggwebservicesrequest.php.
ggWebservicesRequest::payload () abstract
Returns the request payload encoded according to its specific protocol (in HTTP terms, this is the message body).
This function is called client-side.
Returns
string
ggWebservicesRequest::requestHeaders ()
Definition at line 100 of file ggwebservicesrequest.php.
ggWebservicesRequest::requestURI ($uri)
Returns the final URI that will be used by the client, based on its initial version (except the protocol://host:port part).
Useful for protocols that encode parameters in the URL and use GET instead of POST. Default is not to touch the url received and give it back intact. Override it in case of need.
Parameters
string $uri
Returns
string
Definition at line 48 of file ggwebservicesrequest.php.
Member Data Documentation
ggWebservicesRequest::$ContentType = '' protected
Definition at line 112 of file ggwebservicesrequest.php.
Referenced by contentType().
ggWebservicesRequest::$Name protected
Definition at line 108 of file ggwebservicesrequest.php.
Referenced by name(), ggRESTRequest\payload(), ggRESTRequest\requestURI(), and ggeZJSCoreRequest\requestURI().
ggWebservicesRequest::$Parameters = array() protected
Contains the request parameters.
Definition at line 106 of file ggwebservicesrequest.php.
Referenced by parameters(), and ggRESTRequest\payload().
ggWebservicesRequest::$Verb = '' protected
Definition at line 110 of file ggwebservicesrequest.php.
The documentation for this class was generated from the following file:
classes/ggwebservicesrequest.php