ggwebservices: ggeZWebservices Class Reference
ggeZWebservices Class Reference
helper class, used as container for generic functions used throughout the extension
Static Public Member Functions
static appendLogEntry ($logString, $debuglevel)
Logs the string $logString to the logfile webservices.log in the current log directory (usually var/log).
static checkAccess ($functionName, $user=null)
Used by the permission system: check if current user has access to ws method.
static checkAccessToServer ($remoteserver, $user=null)
static classInspect ($classname)
Somehow inspired by ezPODocScanner::objInspect() Lists the publicly accessible properties of a class as an array name => type NB: returns php types, not xsd ones.
static configFileByProtocol ($protocol)
Returns the name of the ini file used to store info about a particular protocol.
static ezpI18ntr ($context, $message, $comment=null, $argument=null)
Wrapper method to translate labels and eventually takes advantage of new 4.3 i18n API.
static eZTemplateFactory ()
Wrapper method to initialize a template and eventually takes advantage of new 4.3 TPL API.
static getMethodsList ($protocol=null)
Function used for perms checking: list of defined ws methods.
static getServersList ()
Function used for perms checking: list of defined ws servers.
static isLoggingEnabled ($debuglevel)
Return true if logging is enabled.
static isRegisterAllProtocolsFunctionsEnabled ()
static methodsWSDL ($server, $methods, $service_name='', $return_url=false, $version=1, $output_type='wsdl', $external_typedefs=false)
Returns the wsdl file corresponding to a list of server's methods.
static methodsXSD ($server, $methods, $service_name='', $return_url=false)
Returns the xml schema corresponding to a list of server's method's complex types.
static registerAvailableMethods ($server, $protocol=null, $forceSingleProtocol=false)
Function used to register php code into a ws server If isRegisterAllProtocolsFunctionsEnabled() == true, will register functions declared for all protocols, regardless of tha value of $protocol, unless $forceSingleProtocol is set to true.
Static Public Attributes
static $debuglevel = -1
static $errorlevels
static $protocolconfigs = array('soap' => 'soap.ini', 'jsonrpc' => 'wsproviders.ini', 'xmlrpc' => 'wsproviders.ini', 'rest' => 'wsproviders.ini')
static $serverprotocols = array('soap', 'jsonrpc', 'xmlrpc', 'rest')
Static Protected Member Functions
static typeFromDocComment ($doc)
Detailed Description
helper class, used as container for generic functions used throughout the extension
Author
G. Giunta
Carlos Revillo
Copyright
(C) 2009-2013 G. Giunta code licensed under the GPL License: see LICENSE file
Definition at line 11 of file ggezwebservices.php.
Member Function Documentation
static ggeZWebservices::appendLogEntry ($logString, $debuglevel) static
Logs the string $logString to the logfile webservices.log in the current log directory (usually var/log).
If logging is disabled, nothing is done.
In dev mode, also writes to the eZP logs to ease debugging (this happens regardless of the logging level set for the extension itself)
Definition at line 37 of file ggezwebservices.php.
Referenced by ggeZWebservicesClient\_call().
static ggeZWebservices::checkAccess ($functionName, $user = null) static
Used by the permission system: check if current user has access to ws method.
Parameters
string $functionName
ezuser $user
Definition at line 475 of file ggezwebservices.php.
Referenced by ezp_authandexec().
static ggeZWebservices::checkAccessToServer ($remoteserver, $user = null) static
Definition at line 520 of file ggezwebservices.php.
static ggeZWebservices::classInspect ($classname) static
Somehow inspired by ezPODocScanner::objInspect() Lists the publicly accessible properties of a class as an array name => type NB: returns php types, not xsd ones.
Todo:
move to another class?
Definition at line 390 of file ggezwebservices.php.
Referenced by ggWebservicesOperators\modify().
static ggeZWebservices::configFileByProtocol ($protocol) static
Returns the name of the ini file used to store info about a particular protocol.
This allows to have soap settings in soap.ini and settings for other webservices in wsproviders.ini NB: shall we return wsproviders.ini on not-found rather than null (= site.ini)?
Parameters
string $protocol
Returns
string
Definition at line 556 of file ggezwebservices.php.
static ggeZWebservices::ezpI18ntr ($context, $message, $comment = null, $argument = null) static
Wrapper method to translate labels and eventually takes advantage of new 4.3 i18n API.
Parameters
$context
$message
$comment
$argument
Returns
string
Definition at line 569 of file ggezwebservices.php.
static ggeZWebservices::eZTemplateFactory () static
Wrapper method to initialize a template and eventually takes advantage of new 4.3 TPL API.
Returns
eZTemplate
Definition at line 587 of file ggezwebservices.php.
static ggeZWebservices::getMethodsList ($protocol = null) static
Function used for perms checking: list of defined ws methods.
NB: to get the list of functions, we have to include some php files that define them. We hope that those files have no side effects, but it's left up to the single coder's style...
Parameters
string $protocol If null, functions for all supported protocols will be listed (soap, xmlrpc, jsonrpc)
Returns
array 2-level array, in the form needed by the permission system
Todo:
find a way to retain name/id association even if list of existing webservices change...
Definition at line 151 of file ggezwebservices.php.
static ggeZWebservices::getServersList () static
Function used for perms checking: list of defined ws servers.
Todo:
log warning ???
Definition at line 118 of file ggezwebservices.php.
static ggeZWebservices::isLoggingEnabled ($debuglevel) static
Return true if logging is enabled.
Definition at line 91 of file ggezwebservices.php.
Referenced by ggeZWebservicesClient\_call().
static ggeZWebservices::isRegisterAllProtocolsFunctionsEnabled () static
Returns
bool
Definition at line 464 of file ggezwebservices.php.
static ggeZWebservices::methodsWSDL ($server, $methods, $service_name = '', $return_url = false, $version = 1, $output_type = 'wsdl', $external_typedefs = false) static
Returns the wsdl file corresponding to a list of server's methods.
This is implemented here because . it relies on the templating system . it does its own caching but it should really be a function of the server class itself. Since we do not want to pollute server classes with eZ specifics, we chose to avoid the reverse depenency by putting the code here.
Todo:
avoid parameter creep: use an options array
Todo:
!important we could build directly html output using an html template, to reduce resource usage
Todo:
we should use different service names if, depending on permissions, user cannot see all methods...
Todo:
if user wants HTML out, give him a en error page...
Definition at line 223 of file ggezwebservices.php.
Referenced by ggPhpSOAPServer\processRequestObj().
static ggeZWebservices::methodsXSD ($server, $methods, $service_name = '', $return_url = false) static
Returns the xml schema corresponding to a list of server's method's complex types.
This is implemented here because . it relies on the templating system . it does its own caching but it should really be a function of the server class itself. Since we do not want to pollute server classes with eZ specifics, we chose to avoid the reverse depenency by putting the code here.
Todo:
!important we could build directly html output using an html template, to reduce resource usage
Todo:
we should use different service names if, depending on permissions, user cannot see all methods...
Definition at line 326 of file ggezwebservices.php.
static ggeZWebservices::registerAvailableMethods ($server, $protocol = null, $forceSingleProtocol = false) static
Function used to register php code into a ws server If isRegisterAllProtocolsFunctionsEnabled() == true, will register functions declared for all protocols, regardless of tha value of $protocol, unless $forceSingleProtocol is set to true.
Parameters
ggWebservicesServer $server
string $protocol if null php functions available for all protocols will be registered
bool $forceSingleProtocol overrides the ini parameter RegisterAllProtocolsFunctions
Definition at line 193 of file ggezwebservices.php.
static ggeZWebservices::typeFromDocComment ($doc) static protected
Definition at line 456 of file ggezwebservices.php.
Member Data Documentation
ggeZWebservices::$debuglevel = -1 static
Definition at line 23 of file ggezwebservices.php.
Referenced by appendLogEntry(), and isLoggingEnabled().
ggeZWebservices::$errorlevels static
Initial value:
= array(
        'info' => 6,
        'notice' => 5,
        'debug' => 4,
        'warning' => 3,
        'error' => 2,
        'critical' => 1,
        'none' => 0)
Definition at line 14 of file ggezwebservices.php.
ggeZWebservices::$protocolconfigs = array('soap' => 'soap.ini', 'jsonrpc' => 'wsproviders.ini', 'xmlrpc' => 'wsproviders.ini', 'rest' => 'wsproviders.ini') static
Definition at line 27 of file ggezwebservices.php.
ggeZWebservices::$serverprotocols = array('soap', 'jsonrpc', 'xmlrpc', 'rest') static
Definition at line 25 of file ggezwebservices.php.
The documentation for this class was generated from the following file:
classes/ggezwebservices.php