ggwebservices: xmlrpcmsg Class Reference
xmlrpcmsg Class Reference
Public Member Functions
addParam ($par)
Add a parameter to the list of parameters to be used upon method invocation.
createPayload ($charset_encoding='')
private
getNumParams ()
Returns the number of parameters in the messge.
getParam ($i)
Returns the nth parameter in the message.
kindOf ()
private
method ($meth='')
Gets/sets the xmlrpc method to be invoked.
& parseResponse ($data='', $headers_processed=false, $return_type='xmlrpcvals')
Parse the xmlrpc response contained in the string $data and return an xmlrpcresp object.
& parseResponseFile ($fp)
Given an open file handle, read all data available and parse it as axmlrpc response.
& parseResponseHeaders (&$data, $headers_processed=false)
Parses HTTP headers and separates them from data.
serialize ($charset_encoding='')
Returns xml representation of the message.
xml_footer ()
private
xml_header ($charset_encoding='')
private
xmlrpcmsg ($meth, $pars=0)
Public Attributes
$content_type = 'text/xml'
$debug =0
$methodname
$params =array()
$payload
Detailed Description
Definition at line 2104 of file xmlrpc.inc.php.
Member Function Documentation
xmlrpcmsg::addParam ($par)
Add a parameter to the list of parameters to be used upon method invocation.
Parameters
xmlrpcval $par
Returns
boolean false on failure public
Definition at line 2213 of file xmlrpc.inc.php.
Referenced by xmlrpcmsg().
xmlrpcmsg::createPayload ($charset_encoding = '')
private
Definition at line 2162 of file xmlrpc.inc.php.
Referenced by serialize().
xmlrpcmsg::getNumParams ()
Returns the number of parameters in the messge.
Returns
integer the number of parameters currently set public
Definition at line 2240 of file xmlrpc.inc.php.
xmlrpcmsg::getParam ($i)
Returns the nth parameter in the message.
The index zero-based.
Parameters
integer $i the index of the parameter to fetch (zero based)
Returns
xmlrpcval the i-th parameter public
Definition at line 2233 of file xmlrpc.inc.php.
xmlrpcmsg::kindOf ()
private
Definition at line 2154 of file xmlrpc.inc.php.
xmlrpcmsg::method ($meth = '')
Gets/sets the xmlrpc method to be invoked.
Parameters
string $meth the method to be set (leave empty not to set it)
Returns
string the method that will be invoked public
Definition at line 2187 of file xmlrpc.inc.php.
& xmlrpcmsg::parseResponse ($data = '', $headers_processed = false, $return_type = 'xmlrpcvals')
Parse the xmlrpc response contained in the string $data and return an xmlrpcresp object.
Parameters
string $data the xmlrpc response, eventually including http headers
bool $headers_processed when true prevents parsing HTTP headers for interpretation of content-encoding and consequent decoding
string $return_type decides return type, i.e. content of response->value(). Either 'xmlrpcvals', 'xml' or 'phpvals'
Returns
xmlrpcresp public
Todo:
return an error msg if $data=='' ?
Todo:
echo something for user?
Todo:
we should test here if server sent an int and a string, and/or coerce them into such...
Definition at line 2508 of file xmlrpc.inc.php.
Referenced by parseResponseFile().
& xmlrpcmsg::parseResponseFile ($fp)
Given an open file handle, read all data available and parse it as axmlrpc response.
NB: the file handle is not closed by this function. NNB: might have trouble in rare cases to work on network streams, as we check for a read of 0 bytes instead of feof($fp). But since checking for feof(null) returns false, we would risk an infinite loop in that case, because we cannot trust the caller to give us a valid pointer to an open file... public
Returns
xmlrpcresp
Todo:
add 2nd & 3rd param to be passed to ParseResponse() ???
Definition at line 2254 of file xmlrpc.inc.php.
& xmlrpcmsg::parseResponseHeaders (& $data, $headers_processed = false)
Parses HTTP headers and separates them from data.
private
Todo:
some other headers (the ones that allow a CSV list of values) do allow many values to be passed using multiple header lines. We should add content to $GLOBALS['_xh']['headers'][$header_name] instead of replacing it for those...
Todo:
with version 1 cookies, we should strip leading and trailing " chars
Todo:
version1 cookies might span multiple lines, thus breaking the parsing above
Definition at line 2270 of file xmlrpc.inc.php.
Referenced by ezjscoremsg\parseResponse(), jsonrpcmsg\parseResponse(), and parseResponse().
xmlrpcmsg::serialize ($charset_encoding = '')
Returns xml representation of the message.
XML prologue included
Returns
string the xml representation of the message, xml prologue included public
Definition at line 2201 of file xmlrpc.inc.php.
xmlrpcmsg::xml_footer ()
private
Definition at line 2146 of file xmlrpc.inc.php.
Referenced by createPayload().
xmlrpcmsg::xml_header ($charset_encoding = '')
private
Definition at line 2131 of file xmlrpc.inc.php.
Referenced by createPayload().
xmlrpcmsg::xmlrpcmsg ($meth, $pars = 0)
Parameters
string $meth the name of the method to invoke
array $pars array of parameters to be paased to the method (xmlrpcval objects)
Definition at line 2116 of file xmlrpc.inc.php.
Referenced by jsonrpcmsg\jsonrpcmsg().
Member Data Documentation
xmlrpcmsg::$content_type = 'text/xml'
Definition at line 2110 of file xmlrpc.inc.php.
xmlrpcmsg::$debug =0
Definition at line 2109 of file xmlrpc.inc.php.
xmlrpcmsg::$methodname
Definition at line 2107 of file xmlrpc.inc.php.
Referenced by method().
xmlrpcmsg::$params =array()
Definition at line 2108 of file xmlrpc.inc.php.
Referenced by jsonrpcmsg\createPayload().
xmlrpcmsg::$payload
Definition at line 2106 of file xmlrpc.inc.php.
Referenced by serialize().
The documentation for this class was generated from the following file:
lib/xmlrpc/xmlrpc.inc.php