ggwebservices: ggWebservicesServer Class Reference
ggWebservicesServer Class Reference
Base class for handling all incoming webservice calls.
Public Member Functions
__construct ($raw_data=null)
Creates a new server object If raw_data is not passed to it, it initializes self from POST data.
handleInternalRequest ($functionName, $params)
Handle execution of server-reserved webservice methods.
handleRequest ($functionName, $params)
Verifies if the given request has been registered as an exposed webservice and executes it.
inflateRequest ($data)
isInternalRequest ($functionName)
Return true if the webservice method encapsulated by $request is to be handled internally by the server instead of a registered function.
methodDescription ($method)
methodSignatures ($method)
parseRequest ($payload)
Takes as input the request payload (body) and returns a request obj or false.
prepareResponse ($response)
To be subclassed.
processRequest ()
Processes the request and prints out the proper response.
registeredMethods ()
Returns the list of available webservices.
registerFunction ($name, $params=null, $result='mixed', $description='')
Registers a new function on the server.
registerObject ($objectName, $includeFile=null)
Registers all functions of an object on the server.
showResponse ($functionName, $namespaceURI, &$value)
Echoes the response, setting http headers and such.
validateParams ($params, $paramDesc)
Check type (and possibly names) of incoming params against the registered method signature (called once per existing sig if method registerd multiple times with different sigs) To be overridden by descendent classes.
Public Attributes
$exception_handling = 0
Controls behaviour of server when invoked user function throws an exception: 0 = catch it and return an 'internal error' xmlrpc response (default) 1 = catch it and return an xmlrpc response with the error corresponding to the exception 2 = allow the exception to float to the upper layers.
$RawPostData
Contains the RAW HTTP post data information.
const GENERICRESPONSEERROR = -205
const GENERICRESPONSESTRING = 'Internal server error'
const INVALIDAUTHERROR = -206
const INVALIDAUTHSTRING = 'Invalid authentication or not enough rights'
const INVALIDCOMPRESSIONERROR = -207
const INVALIDCOMPRESSIONSTRING = 'Request received from client could not be reinflated'
const INVALIDINTROSPECTIONERROR = -204
const INVALIDINTROSPECTIONSTRING = 'Can\'t introspect: method unknown'
const INVALIDMETHODERROR = -202
const INVALIDMETHODSTRING = 'Method not found'
const INVALIDPARAMSERROR = -203
const INVALIDPARAMSSTRING = 'Parameters not matching method'
const INVALIDREQUESTERROR = -201
const INVALIDREQUESTSTRING = 'Request received from client is not valid according to protocol format'
Protected Attributes
$FunctionDescription = array()
$FunctionList = array()
Contains a list over registered functions, and their dscriptions.
$ResponseClass = 'ggWebservicesResponse'
Detailed Description
Base class for handling all incoming webservice calls.
API based on the eZSOAPServer class from eZP. See docs in there.
Process of handling incoming requests:
processRequest | – parseRequest (builds a request obj out of received data) | – handleRequest or handleInternalRequest (builds response as plain php value) | – showResponse (echoes response in correct format, usually via building a response obj and serializing it) | – prepareResponse (adds to response obj any missing info gathered usually during parseRequest)
Author
G. Giunta
Copyright
(C) 2009-2013 G. Giunta
Todo:
add a better way to register methods, supporting definition of type of return value and per-param help text
add propert property support, for $exception_handling and future ones
Definition at line 25 of file ggwebservicesserver.php.
Constructor & Destructor Documentation
ggWebservicesServer::__construct ($raw_data = null)
Creates a new server object If raw_data is not passed to it, it initializes self from POST data.
Definition at line 48 of file ggwebservicesserver.php.
Member Function Documentation
ggWebservicesServer::handleInternalRequest ($functionName, $params)
Handle execution of server-reserved webservice methods.
Returns a php value (or fault object). Used to handle eg system.* stuff in xmlrpc or json. Called by processRequest. To be overridden by descendent classes.
Definition at line 293 of file ggwebservicesserver.php.
Referenced by processRequest().
ggWebservicesServer::handleRequest ($functionName, $params)
Verifies if the given request has been registered as an exposed webservice and executes it.
Called by processRequest.
Definition at line 221 of file ggwebservicesserver.php.
Referenced by processRequest().
ggWebservicesServer::inflateRequest ($data)
Todo:
use pass-by-ref to save memory (!important)
if content-type is application/x-www-form-urlencoded, we should rebuild $_POST
Definition at line 173 of file ggwebservicesserver.php.
Referenced by ggPhpSOAPServer\processRequest(), and processRequest().
ggWebservicesServer::isInternalRequest ($functionName)
Return true if the webservice method encapsulated by $request is to be handled internally by the server instead of a registered function.
Used to handle eg system.* stuff in xmlrpc or json. To be overridden by descendent classes.
Definition at line 281 of file ggwebservicesserver.php.
Referenced by processRequest(), and registerFunction().
ggWebservicesServer::methodDescription ($method)
Todo:
throw an error if method is not registered
Definition at line 384 of file ggwebservicesserver.php.
ggWebservicesServer::methodSignatures ($method)
Todo:
throw an error if method is not registered
Definition at line 390 of file ggwebservicesserver.php.
ggWebservicesServer::parseRequest ($payload) abstract
Takes as input the request payload (body) and returns a request obj or false.
Referenced by processRequest().
ggWebservicesServer::prepareResponse ($response)
To be subclassed.
A function executed before calling payload() on the response object to generate the response stream. Useful to inject into the response some missing data.
Definition at line 105 of file ggwebservicesserver.php.
Referenced by showResponse().
ggWebservicesServer::processRequest ()
Processes the request and prints out the proper response.
Todo:
if function gzinflate does not exist, we should return a more appropriate http-level error
Todo:
dechunk, correct encoding, check for supported http features of the client, etc...
Todo:
use is_a instead
Definition at line 118 of file ggwebservicesserver.php.
ggWebservicesServer::registeredMethods ()
Returns the list of available webservices.
Returns
array
Definition at line 378 of file ggwebservicesserver.php.
ggWebservicesServer::registerFunction ($name, $params = null, $result = 'mixed', $description = '')
Registers a new function on the server.
If params is an array of name => type strings, params will be checked for consistency. Multiple signatures can be registered for a given php function (but only one help text)
Returns
bool Returns false if the function could not be registered.
Todo:
add optional introspection-based param registering
Definition at line 337 of file ggwebservicesserver.php.
ggWebservicesServer::registerObject ($objectName, $includeFile = null)
Registers all functions of an object on the server.
Returns
bool Returns false if the object could not be registered.
Todo:
add optional introspection-based param registering
add single method registration
add registration of per-method descriptions
Todo:
check also for magic methods not to be registered!
Definition at line 307 of file ggwebservicesserver.php.
ggWebservicesServer::showResponse ($functionName, $namespaceURI, & $value)
Echoes the response, setting http headers and such.
Todo:
it would be easier if the request object was passed to this method. Right now we are forced to duplicate extra info coming from the request into the server itself, to reinject it into the response using the prepareResponse() method. Examples: request ID for jsonrpc, desired response type for rest protocol.
Todo:
test how this interacts with php/apache later deflating response
Todo:
this is mandatory eg. for xmlrpc, but if client uses http 1.1, we could omit it for other protocols
Definition at line 68 of file ggwebservicesserver.php.
Referenced by ggPhpSOAPServer\processRequest(), processRequest(), and ggPhpSOAPServer\processRequestObj().
ggWebservicesServer::validateParams ($params, $paramDesc)
Check type (and possibly names) of incoming params against the registered method signature (called once per existing sig if method registerd multiple times with different sigs) To be overridden by descendent classes.
Returns
bool
Definition at line 369 of file ggwebservicesserver.php.
Referenced by handleRequest().
Member Data Documentation
ggWebservicesServer::$exception_handling = 0
Controls behaviour of server when invoked user function throws an exception: 0 = catch it and return an 'internal error' xmlrpc response (default) 1 = catch it and return an xmlrpc response with the error corresponding to the exception 2 = allow the exception to float to the upper layers.
Definition at line 407 of file ggwebservicesserver.php.
ggWebservicesServer::$FunctionDescription = array() protected
Definition at line 397 of file ggwebservicesserver.php.
ggWebservicesServer::$FunctionList = array() protected
Contains a list over registered functions, and their dscriptions.
Definition at line 396 of file ggwebservicesserver.php.
ggWebservicesServer::$RawPostData
Contains the RAW HTTP post data information.
Definition at line 399 of file ggwebservicesserver.php.
Referenced by ggPhpSOAPServer\processRequest(), and processRequest().
ggWebservicesServer::$ResponseClass = 'ggWebservicesResponse' protected
Definition at line 409 of file ggwebservicesserver.php.
Referenced by showResponse().
const ggWebservicesServer::GENERICRESPONSEERROR = -205
Definition at line 32 of file ggwebservicesserver.php.
const ggWebservicesServer::GENERICRESPONSESTRING = 'Internal server error'
Definition at line 40 of file ggwebservicesserver.php.
const ggWebservicesServer::INVALIDAUTHERROR = -206
Definition at line 33 of file ggwebservicesserver.php.
Referenced by ezp_authandexec(), and ggRESTResponse\payload().
const ggWebservicesServer::INVALIDAUTHSTRING = 'Invalid authentication or not enough rights'
Definition at line 41 of file ggwebservicesserver.php.
Referenced by ezp_authandexec().
const ggWebservicesServer::INVALIDCOMPRESSIONERROR = -207
Definition at line 34 of file ggwebservicesserver.php.
Referenced by ggRESTResponse\payload().
const ggWebservicesServer::INVALIDCOMPRESSIONSTRING = 'Request received from client could not be reinflated'
Definition at line 42 of file ggwebservicesserver.php.
const ggWebservicesServer::INVALIDINTROSPECTIONERROR = -204
Definition at line 31 of file ggwebservicesserver.php.
Referenced by ggwebservicesJSCFunctions\methodHelp().
const ggWebservicesServer::INVALIDINTROSPECTIONSTRING = 'Can\'t introspect: method unknown'
Definition at line 39 of file ggwebservicesserver.php.
Referenced by ggwebservicesJSCFunctions\methodHelp().
const ggWebservicesServer::INVALIDMETHODERROR = -202
Definition at line 29 of file ggwebservicesserver.php.
Referenced by ggRESTResponse\payload().
const ggWebservicesServer::INVALIDMETHODSTRING = 'Method not found'
Definition at line 37 of file ggwebservicesserver.php.
const ggWebservicesServer::INVALIDPARAMSERROR = -203
Definition at line 30 of file ggwebservicesserver.php.
Referenced by ggwebservicesJSCFunctions\methodHelp(), and ggRESTResponse\payload().
const ggWebservicesServer::INVALIDPARAMSSTRING = 'Parameters not matching method'
Definition at line 38 of file ggwebservicesserver.php.
Referenced by ggwebservicesJSCFunctions\methodHelp().
const ggWebservicesServer::INVALIDREQUESTERROR = -201
Definition at line 28 of file ggwebservicesserver.php.
Referenced by ggRESTResponse\payload().
const ggWebservicesServer::INVALIDREQUESTSTRING = 'Request received from client is not valid according to protocol format'
Definition at line 36 of file ggwebservicesserver.php.
The documentation for this class was generated from the following file:
classes/ggwebservicesserver.php