ggwebservices: ggRESTRequest Class Reference
ggRESTRequest Class Reference
Class used to wrap 'REST' requests.
Public Member Functions
contentType ()
decodeStream ($rawRequest)
Unlike other requests, $rawRequest here is not used, as GET params are used, and for POST we rely on $_POST as it is already there for us.
getHttpAccept ()
Method used server-side to retrieve the accepted value from HTTP.
jsonpCallback ()
payload ()
No request body for GET requests, as all params are put in the url.
requestHeaders ()
requestURI ($uri)
Final part of url that is built REST style: /methodName?p1=val1&p2=val2 unless request is POST (or other non-GET), then they are sent as part of body.
responseType ()
New method in this subclass.
setAccept ($value)
setContentType ($typeAlias)
Only sets content-type header if we know how to serialize it later.
setExtraHeader ($name, $value)
Used to add custom HTTP headers besides common ones (content-type, accept, auth, proxies, content-encoding, accept-encoding)
setMethod ($method)
Allow easily swapping REST requests from GET to POST and viceversa.
setNameVar ($var)
Allow easily changing the format of serialized requests: where to put called method name (GET/POST var, if null as last element in url path)
setResponseType ($value)
used to force type of expected response instead of finding the type from http headers (when used by client class)
Public Member Functions inherited from ggWebservicesRequest
__construct ($name='', $parameters=array())
addParameter ($name, $value)
This call should be reversed: addParameter($value, $name='') to better support protocols with positional params.
addParameters ($params)
contentType ()
decodeStream ($rawRequest)
Used by servers when decoding incoming requests from the http request received.
method ()
as in 'http verb'. This is not the method name of the request.
name ()
Returns the request name.
parameters ()
payload ()
Returns the request payload encoded according to its specific protocol (in HTTP terms, this is the message body).
requestHeaders ()
requestURI ($uri)
Returns the final URI that will be used by the client, based on its initial version (except the protocol://host:port part).
Static Public Member Functions
static knownContentTypes ()
Protected Member Functions
_payload ($params)
mimeTypeToEncodeType ($type)
Protected Attributes
$Accept = 'application/json, text/xml; q=0.5'
$ContentType = 'application/x-www-form-urlencoded'
$ExtraHeaders = array()
$FormatVar = 'ContentType'
name of GET variable used to specify desired output format.
$JsonpCallback = false
where we store the callback received in the request
$JsonpRegexp = '/^\w+$/'
Regexp used to avoid XSS attacks on jsonp: only callbacks matching this expression are accepted.
$JsonpVar = 'callback'
name of GET variable used for jsonp output 'callback' is used by Yahoo, possibly google too.
$NameVar = null
name of GET variable used to specify method name.
$ResponseType = ''
$Verb = 'GET'
Protected Attributes inherited from ggWebservicesRequest
$ContentType = ''
$Name
$Parameters = array()
Contains the request parameters.
$Verb = ''
Static Protected Attributes
static $KnownContentTypes
Detailed Description
Class used to wrap 'REST' requests.
Author
G. Giunta
Copyright
(C) 2009-2013 G. Giunta
Definition at line 9 of file ggrestrequest.php.
Member Function Documentation
ggRESTRequest::_payload ($params) protected
Parameters
array $params
Returns
string
Definition at line 86 of file ggrestrequest.php.
Referenced by payload(), and requestURI().
ggRESTRequest::contentType ()
Definition at line 238 of file ggrestrequest.php.
ggRESTRequest::decodeStream ($rawRequest)
Unlike other requests, $rawRequest here is not used, as GET params are used, and for POST we rely on $_POST as it is already there for us.
This is a small break of the encapsulation principle of the API, but is faster than having to push this into a specific server class. While at it, we examine request headers also to determine response type for later. Q: what if req. body is not multipart/form-data? A: we just ignore it...
recover method name from the last fragment in the URL
Todo:
test if this is the good var to use for both cgi mode and when rewrite rules are in effect
Definition at line 127 of file ggrestrequest.php.
ggRESTRequest::getHttpAccept ()
Method used server-side to retrieve the accepted value from HTTP.
Same logic as used by ezjscore for the 'call' view, but tries to respect weights in http Accept header
Todo:
(!important) recover $aliasList form the response class
Todo:
add txt, html, php, phps to the list - be loyal to other class methods
Definition at line 172 of file ggrestrequest.php.
Referenced by decodeStream().
ggRESTRequest::jsonpCallback ()
Definition at line 275 of file ggrestrequest.php.
static ggRESTRequest::knownContentTypes () static
Definition at line 251 of file ggrestrequest.php.
ggRESTRequest::mimeTypeToEncodeType ($type) protected
Parameters
string $type
Returns
string
Todo:
make more generic, incl. usage of self::$KnownContentTypes
Definition at line 345 of file ggrestrequest.php.
Referenced by _payload(), and setContentType().
ggRESTRequest::payload ()
No request body for GET requests, as all params are put in the url.
Definition at line 14 of file ggrestrequest.php.
ggRESTRequest::requestHeaders ()
shall we declare support for insecure stuff such as php and serialized php? NB: this must be accompanied by code that can decode the format in ggRESTResponse
Definition at line 256 of file ggrestrequest.php.
ggRESTRequest::requestURI ($uri)
Final part of url that is built REST style: /methodName?p1=val1&p2=val2 unless request is POST (or other non-GET), then they are sent as part of body.
Note: Flickr uses calls like this: ?method=methodName&p1=val1&p2=val2 Google varies a lot
Definition at line 38 of file ggrestrequest.php.
ggRESTRequest::responseType ()
New method in this subclass.
Definition at line 264 of file ggrestrequest.php.
ggRESTRequest::setAccept ($value)
Parameters
string $value
Definition at line 325 of file ggrestrequest.php.
ggRESTRequest::setContentType ($typeAlias)
Only sets content-type header if we know how to serialize it later.
Parameters
string $typeAlias
Returns
bool
Todo:
should we allow more freedom to caller, and only map very obviously wrong things like "php", json" etc
Definition at line 304 of file ggrestrequest.php.
ggRESTRequest::setExtraHeader ($name, $value)
Used to add custom HTTP headers besides common ones (content-type, accept, auth, proxies, content-encoding, accept-encoding)
Parameters
string $name
string $value
Definition at line 335 of file ggrestrequest.php.
ggRESTRequest::setMethod ($method)
Allow easily swapping REST requests from GET to POST and viceversa.
Parameters
string $method
Definition at line 284 of file ggrestrequest.php.
ggRESTRequest::setNameVar ($var)
Allow easily changing the format of serialized requests: where to put called method name (GET/POST var, if null as last element in url path)
Parameters
string $var
Definition at line 293 of file ggrestrequest.php.
ggRESTRequest::setResponseType ($value)
used to force type of expected response instead of finding the type from http headers (when used by client class)
Definition at line 270 of file ggrestrequest.php.
Member Data Documentation
ggRESTRequest::$Accept = 'application/json, text/xml; q=0.5' protected
Definition at line 394 of file ggrestrequest.php.
ggRESTRequest::$ContentType = 'application/x-www-form-urlencoded' protected
Definition at line 378 of file ggrestrequest.php.
Referenced by contentType().
ggRESTRequest::$ExtraHeaders = array() protected
Definition at line 396 of file ggrestrequest.php.
Referenced by requestHeaders().
ggRESTRequest::$FormatVar = 'ContentType' protected
name of GET variable used to specify desired output format.
ContentType comes from ezjszcore. flickr uses 'format'
Definition at line 367 of file ggrestrequest.php.
Referenced by getHttpAccept().
ggRESTRequest::$JsonpCallback = false protected
where we store the callback received in the request
Definition at line 376 of file ggrestrequest.php.
Referenced by jsonpCallback().
ggRESTRequest::$JsonpRegexp = '/^\w+$/' protected
Regexp used to avoid XSS attacks on jsonp: only callbacks matching this expression are accepted.
= letters, digits, underscore. See also an alternative here: http://www.json-p.org/
Definition at line 374 of file ggrestrequest.php.
ggRESTRequest::$JsonpVar = 'callback' protected
name of GET variable used for jsonp output 'callback' is used by Yahoo, possibly google too.
Flickr uses 'jsoncallback'
Definition at line 370 of file ggrestrequest.php.
Referenced by decodeStream().
ggRESTRequest::$KnownContentTypes static protected
Initial value:
= array(
        'application/x-www-form-urlencoded' => 'application/x-www-form-urlencoded',
        'json' => 'application/json',
        'application/json' => 'application/json',
        'php' => 'application/x-httpd-php',
        'application/x-httpd-php' => 'application/x-httpd-php',
        'application/x-php' => 'application/x-httpd-php',
        'phps' => 'application/vnd.php.serialized',
        'application/vnd.php.serialized' => 'application/vnd.php.serialized'
    )
Definition at line 380 of file ggrestrequest.php.
ggRESTRequest::$NameVar = null protected
name of GET variable used to specify method name.
If empty method name is serialized as last element in url path
Definition at line 364 of file ggrestrequest.php.
Referenced by decodeStream(), payload(), and requestURI().
ggRESTRequest::$ResponseType = '' protected
Definition at line 360 of file ggrestrequest.php.
Referenced by responseType().
ggRESTRequest::$Verb = 'GET' protected
Definition at line 359 of file ggrestrequest.php.
The documentation for this class was generated from the following file:
classes/ggrestrequest.php