ggwebservices: ggWebservicesResponse Class Reference
ggWebservicesResponse Class Reference
Generic class used to wrap webservices responses.
Public Member Functions
__construct ($name='')
charset ()
contentType ()
cookies ()
decodeStream ($request, $stream, $headers=false, $cookies=array(), $statuscode="200")
Decodes the response from a text stream (usually the http response body).
faultCode ()
Returns the fault code.
faultString ()
Returns the fault string.
isFault ()
Returns true if the response was a fault.
name ()
payload ()
Returns the payload for the response (in HTTP terms, the 'message body').
responseHeaders ()
setValue ($value)
Sets the value of the response (plain php value).
statusCode ()
value ()
Returns the response value as plain php value.
Static Public Member Functions
static stripHTTPHeader ($data)
This function imported from php-xmlrpc lib: it is more correct than eZ SOAP client one.
Public Attributes
const GENERICRESPONSEERROR = -302
const GENERICRESPONSESTRING = 'Server error'
const INVALIDRESPONSEERROR = -301
const INVALIDRESPONSESTRING = 'Response received from server is not valid'
Protected Member Functions
decodeStreamCommon ($request, $stream, $headers=false, $cookies=array(), $statuscode="200")
Sets internal members from http data, resets response to be not faulty.
parseContentTypeHeader ($header)
Protected Attributes
$Charset = 'UTF-8'
$ContentType = ''
$Cookies = array()
$FaultCode = false
Contains the fault code.
$FaultString = false
Contains fault string.
$Headers = array()
$IsFault = false
Contains true if the response was a fault.
$Name
Contains the name of the response, i.e. function call name.
$StatusCode = null
$Value = false
Contains the response value.
Detailed Description
Generic class used to wrap webservices responses.
Modeled after eZP Soap equivalent.
Author
G. Giunta
Copyright
(C) 2009-2013 G. Giunta
Definition at line 9 of file ggwebservicesresponse.php.
Constructor & Destructor Documentation
ggWebservicesResponse::__construct ($name = '')
Definition at line 19 of file ggwebservicesresponse.php.
Member Function Documentation
ggWebservicesResponse::charset ()
Definition at line 145 of file ggwebservicesresponse.php.
ggWebservicesResponse::contentType ()
Definition at line 140 of file ggwebservicesresponse.php.
ggWebservicesResponse::cookies ()
Definition at line 155 of file ggwebservicesresponse.php.
ggWebservicesResponse::decodeStream ($request, $stream, $headers = false, $cookies = array(), $statuscode = "200") abstract
Decodes the response from a text stream (usually the http response body).
Sets internal members: Value, IsFault, FaultString and FaultCode Should also set: StatusCode, Charset, ContentType, Headers, Cookies -
See Also
decodeStreamCommon for an easy way to do that Otoh it does not have to care about http status code, as handling http is left to client class Name is not set to response from request - a bit weird... but client injects name using the request one anyway The API is a bit whacky because we want too keep compat with the eZP original version
Parameters
ggWebservicesRequest $request the original request object
string $stream the complete HTTP response in case $headers is false, the response body if $headers is an array
array $headers the http headers received along with the response
string $statuscode http status code
Returns
void (if parsing of stream fails, set isFault to true plus error code and description)
Todo:
debloat this api: use a struct to holad all of this info? see how ezcmvc does it...
ggWebservicesResponse::decodeStreamCommon ($request, $stream, $headers = false, $cookies = array(), $statuscode = "200") protected
Sets internal members from http data, resets response to be not faulty.
We make this code available here instead of in decodeStream, to force child classes them to write their own handlers
Parameters
$request
$stream
bool $headers
array $cookies
string $statuscode
Definition at line 198 of file ggwebservicesresponse.php.
Referenced by ggPhpSOAPResponse\decodeStream(), ggHTTPResponse\decodeStream(), ggXMLRPCResponse\decodeStream(), ggJSONRPCResponse\decodeStream(), ggRESTResponse\decodeStream(), and ggSOAPResponse\decodeStream().
ggWebservicesResponse::faultCode ()
Returns the fault code.
Definition at line 98 of file ggwebservicesresponse.php.
ggWebservicesResponse::faultString ()
Returns the fault string.
Returns
string
Definition at line 107 of file ggwebservicesresponse.php.
ggWebservicesResponse::isFault ()
Returns true if the response was a fault.
Definition at line 90 of file ggwebservicesresponse.php.
ggWebservicesResponse::name ()
Definition at line 165 of file ggwebservicesresponse.php.
ggWebservicesResponse::parseContentTypeHeader ($header) protected
Parameters
string $header
Returns
array 1st element: content-type, 2nd element: charset
Definition at line 174 of file ggwebservicesresponse.php.
Referenced by ggRESTResponse\decodeStream(), and decodeStreamCommon().
ggWebservicesResponse::payload () abstract
Returns the payload for the response (in HTTP terms, the 'message body').
Uses internal members name, value, isFault, faultString and faultCode
Returns
string
ggWebservicesResponse::responseHeaders ()
Definition at line 150 of file ggwebservicesresponse.php.
ggWebservicesResponse::setValue ($value)
Sets the value of the response (plain php value).
If $values is (subclass of) ggWebservicesFault, sets the response to error state.
Definition at line 125 of file ggwebservicesresponse.php.
ggWebservicesResponse::statusCode ()
Definition at line 160 of file ggwebservicesresponse.php.
static ggWebservicesResponse::stripHTTPHeader ($data) static
This function imported from php-xmlrpc lib: it is more correct than eZ SOAP client one.
Definition at line 51 of file ggwebservicesresponse.php.
ggWebservicesResponse::value ()
Returns the response value as plain php value.
Returns
mixed
Definition at line 116 of file ggwebservicesresponse.php.
Member Data Documentation
ggWebservicesResponse::$Charset = 'UTF-8' protected
Definition at line 227 of file ggwebservicesresponse.php.
Referenced by charset(), and ggRESTResponse\decodeStream().
ggWebservicesResponse::$ContentType = '' protected
Definition at line 226 of file ggwebservicesresponse.php.
Referenced by contentType(), ggRESTResponse\decodeStream(), and ggRESTResponse\payload().
ggWebservicesResponse::$Cookies = array() protected
Definition at line 228 of file ggwebservicesresponse.php.
Referenced by cookies().
ggWebservicesResponse::$FaultCode = false protected
Contains the fault code.
Definition at line 220 of file ggwebservicesresponse.php.
Referenced by faultCode().
ggWebservicesResponse::$FaultString = false protected
Contains fault string.
Definition at line 218 of file ggwebservicesresponse.php.
Referenced by faultString().
ggWebservicesResponse::$Headers = array() protected
Definition at line 230 of file ggwebservicesresponse.php.
Referenced by responseHeaders().
ggWebservicesResponse::$IsFault = false protected
Contains true if the response was a fault.
Definition at line 222 of file ggwebservicesresponse.php.
Referenced by isFault().
ggWebservicesResponse::$Name protected
Contains the name of the response, i.e. function call name.
Definition at line 224 of file ggwebservicesresponse.php.
Referenced by name().
ggWebservicesResponse::$StatusCode = null protected
Definition at line 229 of file ggwebservicesresponse.php.
Referenced by statusCode().
ggWebservicesResponse::$Value = false protected
Contains the response value.
Definition at line 216 of file ggwebservicesresponse.php.
Referenced by ggPhpSOAPResponse\payload(), ggHTTPResponse\payload(), ggRESTResponse\payload(), and value().
const ggWebservicesResponse::GENERICRESPONSEERROR = -302
Definition at line 12 of file ggwebservicesresponse.php.
const ggWebservicesResponse::GENERICRESPONSESTRING = 'Server error'
Definition at line 16 of file ggwebservicesresponse.php.
const ggWebservicesResponse::INVALIDRESPONSEERROR = -301
Definition at line 11 of file ggwebservicesresponse.php.
Referenced by ggRESTResponse\decodeStream(), and ggSOAPResponse\decodeStream().
const ggWebservicesResponse::INVALIDRESPONSESTRING = 'Response received from server is not valid'
Todo:
use a single array for all error strings
Definition at line 15 of file ggwebservicesresponse.php.
Referenced by ggSOAPResponse\decodeStream().
The documentation for this class was generated from the following file:
classes/ggwebservicesresponse.php