ggwebservices: xmlrpc_server Class Reference
xmlrpc_server Class Reference
Public Member Functions
add_to_map ($methodname, $function, $sig=null, $doc=false, $sigdoc=false)
Add a method to the dispatch map.
debugmsg ($string)
add a string to the 'internal debug message' (separate from 'user debug message')
echoInput ()
A debugging routine: just echoes back the input packet as a string value DEPRECATED!
execute ($m, $params=null, $paramtypes=null)
Execute a method invoked by the client, checking parameters used.
parseRequest ($data, $req_encoding='')
Parse an xml chunk containing an xmlrpc request and execute the corresponding php function registered with the server.
parseRequestHeaders (&$data, &$req_encoding, &$resp_encoding, &$resp_compression)
Parse http headers received along with xmlrpc request.
serializeDebug ($charset_encoding='')
Return a string with the serialized representation of all debug info.
service ($data=null, $return_payload=false)
Execute the xmlrpc request, printing the response.
setDebug ($in)
Set debug level of server.
verifySignature ($in, $sig)
Verify type and number of parameters received against a list of known signatures.
xml_header ($charset_encoding='')
private
xmlrpc_server ($dispMap=null, $serviceNow=true)
Public Attributes
$accepted_charset_encodings = array()
list of charset encodings natively accepted for requests
$accepted_compression = array()
List of http compression methods accepted by the server for requests.
$allow_system_funcs = true
shall we serve calls to system.* methods?
$compress_response = false
When set to true, it will enable HTTP compression of the response, in case the client has declared its support for compression in the request.
$debug = 1
controls wether the server is going to echo debugging messages back to the client as comments in response body. valid values: 0,1,2,3
$debug_info = ''
Storage for internal debug info private.
$dmap =array()
Array defining php functions exposed as xmlrpc methods by this server private.
$exception_handling = 0
Controls behaviour of server when invoked user function throws an exception: 0 = catch it and return an 'internal error' xmlrpc response (default) 1 = catch it and return an xmlrpc response with the error corresponding to the exception 2 = allow the exception to float to the upper layers.
$functions_parameters_type ='xmlrpcvals'
Defines how functions in dmap will be invoked: either using an xmlrpc msg object or plain php values.
$phpvals_encoding_options = array('auto_dates')
Option used for fine-tuning the encoding the php values returned from functions registered in the dispatch map when the functions_parameters_types member is set to 'phpvals'.
$response_charset_encoding = ''
charset encoding to be used for response.
$user_data = null
Extra data passed at runtime to method handling functions.
Detailed Description
Definition at line 434 of file xmlrpcs.inc.php.
Member Function Documentation
xmlrpc_server::add_to_map ($methodname, $function, $sig = null, $doc = false, $sigdoc = false)
Add a method to the dispatch map.
Parameters
string $methodname the name with which the method will be made available
string $function the php function that will get invoked
array $sig the array of valid method signatures
string $doc method documentation
array $sigdoc the array of valid method signatures docs (one string per param, one for return type) public
Definition at line 703 of file xmlrpcs.inc.php.
xmlrpc_server::debugmsg ($string)
add a string to the 'internal debug message' (separate from 'user debug message')
Parameters
string $strings private
Definition at line 1216 of file xmlrpcs.inc.php.
Referenced by jsonrpc_server\parseRequest(), parseRequest(), parseRequestHeaders(), and service().
xmlrpc_server::echoInput ()
A debugging routine: just echoes back the input packet as a string value DEPRECATED!
Definition at line 1240 of file xmlrpcs.inc.php.
xmlrpc_server::execute ($m, $params = null, $paramtypes = null)
Execute a method invoked by the client, checking parameters used.
Parameters
mixed $m either an xmlrpcmsg obj or a method name
array $params array with method parameters as php types (if m is method name only)
array $paramtypes array with xmlrpc types of method parameters (if m is method name only)
Returns
xmlrpcresp private
Definition at line 1041 of file xmlrpcs.inc.php.
Referenced by parseRequest().
xmlrpc_server::parseRequest ($data, $req_encoding = '')
Parse an xml chunk containing an xmlrpc request and execute the corresponding php function registered with the server.
Parameters
string $data the xml request
string $req_encoding (optional) the charset encoding of the xml request
Returns
xmlrpcresp private
this will fail on PHP 5 if charset is not specified in the xml prologue,
Todo:
use an ampty string for php 5 ???
Definition at line 915 of file xmlrpcs.inc.php.
Referenced by service().
xmlrpc_server::parseRequestHeaders (& $data, & $req_encoding, & $resp_encoding, & $resp_compression)
Parse http headers received along with xmlrpc request.
If needed, inflate request
Returns
null on success or an xmlrpcresp private
Todo:
we should parse q=0.x preferences instead of getting first charset specified...
Todo:
check if mbstring is enabled and automagic input conversion is on: it might mingle with this check???
Definition at line 791 of file xmlrpcs.inc.php.
Referenced by service().
xmlrpc_server::serializeDebug ($charset_encoding = '')
Return a string with the serialized representation of all debug info.
Parameters
string $charset_encoding the target charset encoding for the serialization
Returns
string an XML comment (or two)
Definition at line 557 of file xmlrpcs.inc.php.
Referenced by service().
xmlrpc_server::service ($data = null, $return_payload = false)
Execute the xmlrpc request, printing the response.
Parameters
string $data the request body. If null, the http POST request will be examined
Returns
xmlrpcresp the response object (usually not used by caller...) public
Definition at line 586 of file xmlrpcs.inc.php.
Referenced by xmlrpc_server().
xmlrpc_server::setDebug ($in)
Set debug level of server.
Parameters
integer $in debug lvl: determines info added to xmlrpc responses (as xml comments) 0 = no debug info, 1 = msgs set from user with debugmsg(), 2 = add complete xmlrpc request (headers and body), 3 = add also all processing warnings happened during method processing (NB: this involves setting a custom error handler, and might interfere with the standard processing of the php function exposed as method. In particular, triggering an USER_ERROR level error will not halt script execution anymore, but just end up logged in the xmlrpc response) Note that info added at elevel 2 and 3 will be base64 encoded public
Definition at line 547 of file xmlrpcs.inc.php.
xmlrpc_server::verifySignature ($in, $sig)
Verify type and number of parameters received against a list of known signatures.
Parameters
array $in array of either xmlrpcval objects or xmlrpc type definitions
array $sig array of known signatures to match against private
Definition at line 725 of file xmlrpcs.inc.php.
Referenced by jsonrpc_server\execute(), and execute().
xmlrpc_server::xml_header ($charset_encoding = '')
private
Definition at line 1224 of file xmlrpcs.inc.php.
Referenced by service().
xmlrpc_server::xmlrpc_server ($dispMap = null, $serviceNow = true)
Parameters
array $dispmap the dispatch map withd efinition of exposed services
boolean $servicenow set to false to prevent the server from runnung upon construction
Definition at line 501 of file xmlrpcs.inc.php.
Member Data Documentation
xmlrpc_server::$accepted_charset_encodings = array()
list of charset encodings natively accepted for requests
Definition at line 476 of file xmlrpcs.inc.php.
xmlrpc_server::$accepted_compression = array()
List of http compression methods accepted by the server for requests.
NB: PHP supports deflate, gzip compressions out of the box if compiled w. zlib
Definition at line 472 of file xmlrpcs.inc.php.
xmlrpc_server::$allow_system_funcs = true
shall we serve calls to system.* methods?
Definition at line 474 of file xmlrpcs.inc.php.
xmlrpc_server::$compress_response = false
When set to true, it will enable HTTP compression of the response, in case the client has declared its support for compression in the request.
Definition at line 467 of file xmlrpcs.inc.php.
xmlrpc_server::$debug = 1
controls wether the server is going to echo debugging messages back to the client as comments in response body. valid values: 0,1,2,3
Definition at line 455 of file xmlrpcs.inc.php.
xmlrpc_server::$debug_info = ''
Storage for internal debug info private.
Definition at line 491 of file xmlrpcs.inc.php.
xmlrpc_server::$dmap =array()
Array defining php functions exposed as xmlrpc methods by this server private.
Definition at line 440 of file xmlrpcs.inc.php.
Referenced by jsonrpc_server\execute(), and execute().
xmlrpc_server::$exception_handling = 0
Controls behaviour of server when invoked user function throws an exception: 0 = catch it and return an 'internal error' xmlrpc response (default) 1 = catch it and return an xmlrpc response with the error corresponding to the exception 2 = allow the exception to float to the upper layers.
Definition at line 462 of file xmlrpcs.inc.php.
xmlrpc_server::$functions_parameters_type ='xmlrpcvals'
Defines how functions in dmap will be invoked: either using an xmlrpc msg object or plain php values.
valid strings are 'xmlrpcvals', 'phpvals' or 'epivals'
Definition at line 446 of file xmlrpcs.inc.php.
xmlrpc_server::$phpvals_encoding_options = array('auto_dates')
Option used for fine-tuning the encoding the php values returned from functions registered in the dispatch map when the functions_parameters_types member is set to 'phpvals'.
See Also
php_xmlrpc_encode for a list of values
Definition at line 453 of file xmlrpcs.inc.php.
xmlrpc_server::$response_charset_encoding = ''
charset encoding to be used for response.
NB: if we can, we will convert the generated response from internal_encoding to the intended one. can be: a supported xml encoding (only UTF-8 and ISO-8859-1 at present, unless mbstring is enabled), null (leave unspecified in response, convert output stream to US_ASCII), 'default' (use xmlrpc library default as specified in xmlrpc.inc, convert output stream if needed), or 'auto' (use client-specified charset encoding or same as request if request headers do not specify it (unless request is US-ASCII: then use library default anyway). NB: pretty dangerous if you accept every charset and do not have mbstring enabled)
Definition at line 486 of file xmlrpcs.inc.php.
Referenced by parseRequestHeaders().
xmlrpc_server::$user_data = null
Extra data passed at runtime to method handling functions.
Used only by EPI layer
Definition at line 495 of file xmlrpcs.inc.php.
The documentation for this class was generated from the following file:
lib/xmlrpc/xmlrpcs.inc.php