ggwebservices: xmlrpcval Class Reference
xmlrpcval Class Reference
Public Member Functions
addArray ($vals)
Add an array of xmlrpcval objects to an xmlrpcval.
addScalar ($val, $type='string')
Add a single php value to an (unitialized) xmlrpcval.
addStruct ($vals)
Add an array of named xmlrpcval objects to an xmlrpcval.
arraymem ($m)
Returns the m-th member of an xmlrpcval of struct type.
arraysize ()
Returns the number of members in an xmlrpcval of array type.
dump ($ar)
getval ()
kindOf ()
Returns a string containing "struct", "array" or "scalar" describing the base type of the value.
scalartyp ()
Returns the type of the xmlrpcval.
scalarval ()
Returns the value of a scalar xmlrpcval.
serialize ($charset_encoding='')
Returns xml representation of the value.
serializedata ($typ, $val, $charset_encoding='')
private
serializeval ($o)
structeach ()
Return next member element for xmlrpcvals of type struct.
structmem ($m)
Returns the value of a given struct member (an xmlrpcval object in itself).
structmemexists ($m)
Checks wheter a struct member with a given name is present.
structreset ()
Reset internal pointer for xmlrpcvals of type struct.
structsize ()
Returns the number of members in an xmlrpcval of struct type.
xmlrpcval ($val=-1, $type='')
Public Attributes
$_php_class =null
$me =array()
$mytype =0
Detailed Description
Definition at line 2729 of file xmlrpc.inc.php.
Member Function Documentation
xmlrpcval::addArray ($vals)
Add an array of xmlrpcval objects to an xmlrpcval.
Parameters
array $vals
Returns
int 1 or 0 on failure public
Todo:
add some checking for $vals to be an array of xmlrpcvals?
Definition at line 2855 of file xmlrpc.inc.php.
xmlrpcval::addScalar ($val, $type = 'string')
Add a single php value to an (unitialized) xmlrpcval.
Parameters
mixed $val
string $type
Returns
int 1 or 0 on failure
Definition at line 2799 of file xmlrpc.inc.php.
xmlrpcval::addStruct ($vals)
Add an array of named xmlrpcval objects to an xmlrpcval.
Parameters
array $vals
Returns
int 1 or 0 on failure public
Todo:
add some checking for $vals to be an array?
Definition at line 2884 of file xmlrpc.inc.php.
xmlrpcval::arraymem ($m)
Returns the m-th member of an xmlrpcval of struct type.
Parameters
integer $m the index of the value to be retrieved (zero based)
Returns
xmlrpcval public
Definition at line 3197 of file xmlrpc.inc.php.
xmlrpcval::arraysize ()
Returns the number of members in an xmlrpcval of array type.
Returns
integer public
Definition at line 3207 of file xmlrpc.inc.php.
xmlrpcval::dump ($ar)
Definition at line 2907 of file xmlrpc.inc.php.
xmlrpcval::getval ()
Definition at line 3124 of file xmlrpc.inc.php.
xmlrpcval::kindOf ()
Returns a string containing "struct", "array" or "scalar" describing the base type of the value.
Returns
string public
Definition at line 2927 of file xmlrpc.inc.php.
xmlrpcval::scalartyp ()
Returns the type of the xmlrpcval.
For integers, 'int' is always returned in place of 'i4'
Returns
string public
Definition at line 3180 of file xmlrpc.inc.php.
xmlrpcval::scalarval ()
Returns the value of a scalar xmlrpcval.
Returns
mixed public
Definition at line 3167 of file xmlrpc.inc.php.
xmlrpcval::serialize ($charset_encoding = '')
Returns xml representation of the value.
XML prologue not included
Parameters
string $charset_encoding the charset to be used for serialization. if null, US-ASCII is assumed
Returns
string public
Definition at line 3055 of file xmlrpc.inc.php.
xmlrpcval::serializedata ($typ, $val, $charset_encoding = '')
private
Definition at line 2948 of file xmlrpc.inc.php.
Referenced by serialize(), and serializeval().
xmlrpcval::serializeval ($o)
Definition at line 3067 of file xmlrpc.inc.php.
xmlrpcval::structeach ()
Return next member element for xmlrpcvals of type struct.
Returns
xmlrpcval public
Definition at line 3117 of file xmlrpc.inc.php.
xmlrpcval::structmem ($m)
Returns the value of a given struct member (an xmlrpcval object in itself).
Will raise a php warning if struct member of given name does not exist
Parameters
string $m the name of the struct member to be looked up
Returns
xmlrpcval public
Definition at line 3098 of file xmlrpc.inc.php.
xmlrpcval::structmemexists ($m)
Checks wheter a struct member with a given name is present.
Works only on xmlrpcvals of type struct.
Parameters
string $m the name of the struct member to be looked up
Returns
boolean public
Definition at line 3086 of file xmlrpc.inc.php.
xmlrpcval::structreset ()
Reset internal pointer for xmlrpcvals of type struct.
public
Definition at line 3107 of file xmlrpc.inc.php.
xmlrpcval::structsize ()
Returns the number of members in an xmlrpcval of struct type.
Returns
integer public
Definition at line 3217 of file xmlrpc.inc.php.
xmlrpcval::xmlrpcval ($val = -1, $type = '')
Parameters
mixed $val
string $type any valid xmlrpc type name (lowercase). If null, 'string' is assumed
Todo:
: optimization creep - do not call addXX, do it all inline. downside: booleans will not be coerced anymore
Definition at line 2739 of file xmlrpc.inc.php.
Referenced by addScalar().
Member Data Documentation
xmlrpcval::$_php_class =null
Definition at line 2733 of file xmlrpc.inc.php.
xmlrpcval::$me =array()
Definition at line 2731 of file xmlrpc.inc.php.
xmlrpcval::$mytype =0
Definition at line 2732 of file xmlrpc.inc.php.
The documentation for this class was generated from the following file:
lib/xmlrpc/xmlrpc.inc.php