ggwebservices: modules/webservices/execute.php File Reference
execute.php File Reference
Variables
$access = ggeZWebservices::checkAccess($functionName, $user)
$data = $server->inflateRequest($data)
$module = $Params['Module']
View that executes webservice calls.
if($wsINI->variable(
'GeneralSettings', 'Enable'.$protocol)!=
'true') $namespaceURI = ''
$params = $request->parameters()
$protocol = strtoupper($Params['protocol'])
if($data===false) $request = $server->parseRequest($data)
$server = new $serverClass()
$serverClass = 'gg' . $wsclass . 'Server'
if($wsINI->variable(
'GeneralSettings',
'ValidateClientIPs')==
'enabled') if($wsINI->variable(
'GeneralSettings',
'JscoreIntegration')==
'enabled'&&class_exists(
'ezjscServerRouter')) $user = eZUser::currentUser()
$wsclass = $protocol
switch($protocol) $wsINI = eZINI::instance(ggeZWebservices::configFileByProtocol(strtolower($protocol)))
if(!is_object($request)) if($protocol==
'REST') else
Variable Documentation
$access = ggeZWebservices::checkAccess($functionName, $user)
Definition at line 136 of file execute.php.
Referenced by ggeZWebservices\checkAccess(), ggeZWebservices\checkAccessToServer(), and ezp_authandexec().
$data = $server->inflateRequest($data)
Definition at line 56 of file execute.php.
Referenced by ggWebservicesServer\inflateRequest(), json_encode_entities(), json_parse(), json_parse_native(), jsonrpc_parse_req(), jsonrpc_parse_resp(), ggwebservicesJSCFunctions\listMethods(), ggWebservicesClient\parseHTTPResponse(), jsonrpc_server\parseRequest(), xmlrpc_server\parseRequest(), xmlrpc_server\parseRequestHeaders(), ezjscoremsg\parseResponse(), jsonrpcmsg\parseResponse(), xmlrpcmsg\parseResponse(), xmlrpcmsg\parseResponseFile(), xmlrpcmsg\parseResponseHeaders(), ggPhpSOAPServer\processRequest(), ggWebservicesServer\processRequest(), xmlrpc_server\service(), ggWebservicesResponse\stripHTTPHeader(), ggPhpSOAPClient\toArray(), xmlrpc_cd(), xmlrpc_dh(), and xmlrpc_encode_entitites().
$module = $Params['Module']
View that executes webservice calls.
Author
G. Giunta
Copyright
(C) 2009-2013 G. Giunta code licensed under the GPL License: see LICENSE file
Definition at line 12 of file execute.php.
if ($wsINI->variable('GeneralSettings', 'Enable'.$protocol)!= 'true') $namespaceURI = ''
Todo:
return an http error 500 or something like that ?
Definition at line 43 of file execute.php.
Referenced by ggPhpSOAPServer\processRequest(), and ggWebservicesServer\processRequest().
$params = $request->parameters()
Definition at line 90 of file execute.php.
$protocol = strtoupper($Params['protocol'])
Definition at line 13 of file execute.php.
Referenced by ggXMLRPCClient\__construct(), ggeZJSCoreClient\__construct(), ggJSONRPCClient\__construct(), ggHTTPClient\__construct(), ggPhpSOAPClient\__construct(), ggWebservicesClient\__construct(), ggPhpSOAPClient\_send(), ggeZWebservices\configFileByProtocol(), ggeZWebservices\getMethodsList(), and ggeZWebservices\registerAvailableMethods().
if ($data===false) $request = $server->parseRequest($data)
Definition at line 67 of file execute.php.
$server = new $serverClass()
Definition at line 45 of file execute.php.
$serverClass = 'gg' . $wsclass . 'Server'
Definition at line 44 of file execute.php.
if ($wsINI->variable('GeneralSettings', 'ValidateClientIPs')== 'enabled') if ($wsINI->variable('GeneralSettings', 'JscoreIntegration')== 'enabled'&&class_exists('ezjscServerRouter')) $user = eZUser::currentUser()
Definition at line 135 of file execute.php.
Referenced by ggeZWebservices\checkAccess(), ggeZWebservices\checkAccessToServer(), ezp_authandexec(), and notification_addtonotification().
$wsclass = $protocol
Definition at line 14 of file execute.php.
$wsINI = eZINI::instance(ggeZWebservices::configFileByProtocol(strtolower($protocol)))
Todo:
return an http error 500 or something like that ?
Definition at line 34 of file execute.php.
if (!$access) if ($wsclass== 'PhpSOAP') else
Initial value:
{
    $functionName = $request->name()
Todo:
use is_a instead
Definition at line 87 of file execute.php.