ggwebservices: lib/ezjscore/ezjscore.inc.php File Reference
ezjscore.inc.php File Reference
Classes
class ezjscore_client
eZJSCORE extension to the PHP-XMLRPC lib
class ezjscoremsg
class ezjscoreresp
class ezjscoreval
Functions
serialize_ezjscoreresp ($resp, $charset_encoding='', $format='application/json')
Serialize an ezjscoreresp (or xmlrpcresp/jsonrpcresp ?) as json.
serialize_ezjscoreval ($value, $charset_encoding='')
Serialize an ezjscoreval (or xmlrpcval) as application/x-www-form-urlencoded.
Function Documentation
serialize_ezjscoreresp ($resp, $charset_encoding = '', $format = 'application/json')
Serialize an ezjscoreresp (or xmlrpcresp/jsonrpcresp ?) as json.
Moved outside of the corresponding class to ease multi-serialization of xmlrpcresp objects
Parameters
xmlrpcresp or jsonrpcresp $resp
mixed $id
Returns
string private
Todo:
support xml format, too
Definition at line 265 of file ezjscore.inc.php.
Referenced by ezjscoreresp\serialize().
serialize_ezjscoreval ($value, $charset_encoding = '')
Serialize an ezjscoreval (or xmlrpcval) as application/x-www-form-urlencoded.
Recursive stuff is handles as json (
Todo:
: to be verified...) Moved outside of the corresponding class to ease multi-serialization of xmlrpcval/jsonrpcval objects
Parameters
xmlrpcval or jsonrpcval $value $charset_encoding private
Definition at line 302 of file ezjscore.inc.php.
Referenced by ezjscoremsg\createPayload(), and ezjscoreval\serialize().