ggwebservices: modules/webservices/debugger/frame.php File Reference
frame.php File Reference
Variables
$Result = array()
$Result ['content'] = $tpl->fetch("design:webservices/debugger/frame.tpl")
$Result ['left_menu'] = 'design:parts/wsdebugger/menu.tpl'
$Result ['path']
$target_list = array()
foreach($wsINI->groups() as
$groupname=> $groupdef) $tpl = ggeZWebservices::eZTemplateFactory()
$wsINI = eZINI::instance('wsproviders.ini')
WS debugger: external frame.
Variable Documentation
$Result = array()
Definition at line 222 of file frame.php.
$Result['content'] = $tpl->fetch("design:webservices/debugger/frame.tpl")
Definition at line 223 of file frame.php.
$Result['left_menu'] = 'design:parts/wsdebugger/menu.tpl'
Definition at line 224 of file frame.php.
$Result['path']
Initial value:
= array(array('url' => 'webservices/debugger',
                                'text' => ggeZWebservices::ezpI18ntr( 'extension/webservices', 'WS Debugger' ) ) )
Definition at line 225 of file frame.php.
$target_list = array()
Todo:
parse also all 'Options' that can be set per server
Definition at line 95 of file frame.php.
Referenced by ggeZWebservices\getServersList().
foreach ($wsINI->groups() as $groupname=> $groupdef) $tpl = ggeZWebservices::eZTemplateFactory()
Todo:
also parse from ini forceCURL, requestCompression, acceptedCompression
Definition at line 218 of file frame.php.
foreach (array('xmlrpc', 'jsonrpc', 'ezjscore', 'soap', 'rest v1', 'rest v2') as $i=> $protocol) $wsINI = eZINI::instance('wsproviders.ini')
WS debugger: external frame.
Author
G. Giunta
Copyright
(C) 2010-2013 Gaetano Giunta code licensed under the GPL License: see LICENSE file
Todo:
disable link if ezjscore not active, enable rest v1 and rest v2 ...
Todo:
filter out all cookies except the one for current session ?
Definition at line 12 of file frame.php.
Referenced by ggeZWebservices\getServersList(), ggeZWebservices\isRegisterAllProtocolsFunctionsEnabled(), and ggeZWebservices\registerAvailableMethods().