ggwebservices: modules/webservices/debugger/common.php File Reference
common.php File Reference
Functions
payload_is_safe ($input)
Variables
if(get_magic_quotes_gpc()) if(isset($_GET['usepost'])&&$_GET['usepost']===
'true') $params ['debug'] = false
WS debugger:initialize user parameters received via GET (or POST): set defaults, cleanup.
$params ['protocol'] = 0
$params ['run'] = false
$params ['wstype'] = 0
$params ['id'] = ''
$params ['port'] = ''
$params ['path'] = ''
$params ['action'] = ''
$params ['method'] = ''
$params ['methodsig'] = 0
$params ['payload'] = ''
$params ['alt_payload'] = ''
$params ['username'] = ''
$params ['password'] = ''
$params ['authtype'] = 1
$params ['verifyhost'] = 0
$params ['verifypeer'] = false
$params ['cainfo'] = ''
$params ['proxy'] = ''
$params ['proxyuser'] = ''
$params ['proxypwd'] = ''
$params ['timeout'] = 0
$params ['requestcompression'] = 0
$params ['responsecompression'] = 0
$params ['clientcookies'] = ''
$params ['wsdl'] = 0
$params ['soapversion'] = 0
$params ['namevariable'] = ''
$params ['responsetype'] = ''
$params ['requesttype'] = ''
$params ['verb'] = ''
$params ['accept'] = ''
$params ['extraheaders'] = ''
if(isset($_GET['wsaction'])) else
Function Documentation
payload_is_safe ($input)
Definition at line 153 of file common.php.
Variable Documentation
if (get_magic_quotes_gpc()) if (isset($_GET['usepost'])&&$_GET['usepost']=== 'true') $params['debug'] = false
WS debugger:initialize user parameters received via GET (or POST): set defaults, cleanup.
Author
Gaetano Giunta
Copyright
(C) 2005-2013 G. Giunta code licensed under the BSD License: http://phpxmlrpc.sourceforge.net/license.txt
Todo:
switch params for http compression from 0,1,2 to values to be used directly
do some more sanitization of received parameters
Definition at line 34 of file common.php.
Referenced by ggRESTRequest\_payload(), xmlrpc_client\_try_multicall(), _xmlrpcs_multicall_do_call(), ggWebservicesRequest\addParameters(), jsonrpc_server\execute(), xmlrpc_server\execute(), ezp_authandexec(), ggXMLRPCServer\handleInternalRequest(), ggRESTServer\handleRequest(), ggWebservicesServer\handleRequest(), ggwebservicesJSCFunctions\methodHelp(), ggRESTRequest\payload(), php_jsonrpc_decode_json(), ggWebservicesServer\processRequest(), ggPhpSOAPServer\registerFunction(), ggWebservicesServer\registerFunction(), ggRESTRequest\requestURI(), ggWSDLParser\transformGetFunctionsResults(), and ggXMLRPCServer\validateParams().
$params['protocol'] = 0
Definition at line 35 of file common.php.
$params['run'] = false
Definition at line 36 of file common.php.
$params['wstype'] = 0
Definition at line 37 of file common.php.
$params['id'] = ''
Definition at line 38 of file common.php.
$params['port'] = ''
Definition at line 120 of file common.php.
$params['path'] = ''
Definition at line 121 of file common.php.
$params['action'] = ''
Definition at line 122 of file common.php.
$params['method'] = ''
Definition at line 123 of file common.php.
$params['methodsig'] = 0
Definition at line 124 of file common.php.
$params['payload'] = ''
Definition at line 125 of file common.php.
$params['alt_payload'] = ''
Definition at line 126 of file common.php.
$params['username'] = ''
Definition at line 127 of file common.php.
$params['password'] = ''
Definition at line 128 of file common.php.
$params['authtype'] = 1
Definition at line 129 of file common.php.
$params['verifyhost'] = 0
Definition at line 130 of file common.php.
$params['verifypeer'] = false
Definition at line 131 of file common.php.
$params['cainfo'] = ''
Definition at line 132 of file common.php.
$params['proxy'] = ''
Definition at line 133 of file common.php.
$params['proxyuser'] = ''
Definition at line 134 of file common.php.
$params['proxypwd'] = ''
Definition at line 135 of file common.php.
$params['timeout'] = 0
Definition at line 136 of file common.php.
$params['requestcompression'] = 0
Definition at line 137 of file common.php.
$params['responsecompression'] = 0
Definition at line 138 of file common.php.
$params['clientcookies'] = ''
Definition at line 139 of file common.php.
$params['wsdl'] = 0
Definition at line 141 of file common.php.
$params['soapversion'] = 0
Definition at line 142 of file common.php.
$params['namevariable'] = ''
Definition at line 144 of file common.php.
$params['responsetype'] = ''
Definition at line 145 of file common.php.
$params['requesttype'] = ''
Definition at line 146 of file common.php.
$params['verb'] = ''
Definition at line 147 of file common.php.
$params['accept'] = ''
Definition at line 148 of file common.php.
$params['extraheaders'] = ''
Definition at line 149 of file common.php.
if (isset($_GET['wsaction'])) else
Initial value:
{
    $params['host'] = ''
Definition at line 118 of file common.php.