ggwebservices: cronjobs/rotatewslogs.php File Reference
rotatewslogs.php File Reference
Variables
$fileName = $varDir . '/' . $logDir . '/' . $logName
$ini = eZINI::instance('wsproviders.ini')
Rotate logs of ws calls: since we store them in the per-sa dir, eZ will not do it on its own.
$logDir = 'log'
$logName = 'webservices.log'
$maxFileSize = $ini->variable('GeneralSettings', 'MaxLogSize')
if($maxFileSize<=0) if($ini->
hasVariable('GeneralSettings',
'MaxLogrotateFiles')&&$ini->
variable('GeneralSettings',
'MaxLogrotateFiles') > 0) $varDir = eZSys::varDirectory()
Variable Documentation
$fileName = $varDir . '/' . $logDir . '/' . $logName
Definition at line 28 of file rotatewslogs.php.
Referenced by ggeZWebservices\appendLogEntry().
$ini = eZINI::instance('wsproviders.ini')
Rotate logs of ws calls: since we store them in the per-sa dir, eZ will not do it on its own.
We are very nice people, and allow a custom max file size to be specified instead of relying on eZ default one, and a number of rotated files to be kept, too!
Author
G. Giunta
Copyright
(C) 2009-2013 G. Giunta
Definition at line 12 of file rotatewslogs.php.
Referenced by ggeZWebservicesClient\_call(), ggeZWebservices\appendLogEntry(), ezp_authandexec(), eZUpdateDebugSettings(), eZUpdateTextCodecSettings(), ggeZWebservices\isLoggingEnabled(), ggwebservicesJSCFunctions\listMethods(), and ggwebservicesJSCFunctions\methodHelp().
$logDir = 'log'
Definition at line 26 of file rotatewslogs.php.
Referenced by ggeZWebservices\appendLogEntry().
$logName = 'webservices.log'
Definition at line 27 of file rotatewslogs.php.
Referenced by ggeZWebservices\appendLogEntry().
$maxFileSize = $ini->variable('GeneralSettings', 'MaxLogSize')
Definition at line 13 of file rotatewslogs.php.
if ($maxFileSize<=0) if ($ini->hasVariable('GeneralSettings', 'MaxLogrotateFiles')&&$ini->variable('GeneralSettings', 'MaxLogrotateFiles') > 0) $varDir = eZSys::varDirectory()
Definition at line 25 of file rotatewslogs.php.
Referenced by ggeZWebservices\appendLogEntry().