ggwebservices: doc/samples/soap_client_outside_ezp.php File Reference
soap_client_outside_ezp.php File Reference
Variables
$client = new ggPhpSOAPClient("mssoapinterop.org", "/asmx/simple.asmx", 80, null, 'http://mssoapinterop.org/asmx/simple.asmx?WSDL')
Sample soap client that uses the ggws classes outside of an eZ Publish context The server endpoint in use is the public one from mssoapinterop.org.
$request = new ggPhpSOAPRequest("echoInteger", array(123))
$response = $client->send($request)
if($response->isFault()) else
Variable Documentation
$client = new ggPhpSOAPClient("mssoapinterop.org", "/asmx/simple.asmx", 80, null, 'http://mssoapinterop.org/asmx/simple.asmx?WSDL')
Sample soap client that uses the ggws classes outside of an eZ Publish context The server endpoint in use is the public one from mssoapinterop.org.
Author
Gaetano Giunta
Copyright
(c) 2010-2013 G. Giunta code licensed under the GNU GPL. See LICENSE file
Definition at line 24 of file soap_client_outside_ezp.php.
Referenced by ggPhpSOAPClientTransport\__construct(), ggeZWebservicesClient\_call(), ggHTTPClient\call(), and ggPhpSOAPClient\send().
$request = new ggPhpSOAPRequest("echoInteger", array(123))
Definition at line 29 of file soap_client_outside_ezp.php.
Referenced by ggPhpSOAPClientTransport\__construct(), ggPhpSOAPClientTransport\__doRequest(), ggeZWebservicesClient\_call(), ggPhpSOAPClient\_send(), ggHTTPClient\call(), ggPhpSOAPResponse\decodeStream(), ggHTTPResponse\decodeStream(), ggXMLRPCResponse\decodeStream(), ggJSONRPCResponse\decodeStream(), ggRESTResponse\decodeStream(), ggSOAPResponse\decodeStream(), ggXMLRPCServer\handleInternalRequest(), ggXMLRPCServer\parseRequest(), ggRESTServer\parseRequest(), ggJSONRPCServer\parseRequest(), ggPhpSOAPServer\parseRequest(), ggSOAPRequest\payload(), ggWebservicesClient\payload(), ggPhpSOAPServer\processRequest(), ggWebservicesServer\processRequest(), ggPhpSOAPServer\processRequestObj(), ggRESTClient\send(), ggSOAPClient\send(), and ggPhpSOAPClient\send().
$response = $client->send($request)
Definition at line 35 of file soap_client_outside_ezp.php.
Referenced by ggeZWebservicesResponse\__construct(), ggeZWebservicesClient\_call(), ggPhpSOAPClient\_send(), xmlrpc_client\_try_multicall(), ggHTTPClient\call(), ggSOAPResponse\decodeStream(), ggSOAPResponse\payload(), ggRESTServer\prepareResponse(), ggJSONRPCServer\prepareResponse(), ggWebservicesServer\processRequest(), ggPhpSOAPClient\send(), ggeZWebservicesClient\send(), and ggWebservicesServer\showResponse().
if ($response->isFault()) else
Initial value:
{
    print( "Returned value was: \"" . $response->value() . "\"" )
Definition at line 47 of file soap_client_outside_ezp.php.