ggwebservices: webservicescontroller.php File Reference
webservicescontroller.php File Reference
Functions
eZUpdateDebugSettings ()
Reads settings from site.ini and passes them to eZDebug.
eZUpdateTextCodecSettings ()
Reads settings from i18n.ini and passes them to eZTextCodec.
Variables
$access = changeAccess($access)
$enable = $wsINI->variable('GeneralSettings', 'Enable' . strtoupper(WS_PROTOCOL))
$GLOBALS ['eZRequestedURI'] = $uri
$ini = eZINI::instance()
$moduleRepositories = eZModule::activeModuleRepositories()
$uri = eZURI::instance(eZSys::requestURI())
$wsINI = eZINI::instance(ggeZWebservices::configFileByProtocol(WS_PROTOCOL))
if($wsINI->variable(
'GeneralSettings',
'UseDefaultAccess')===
'enabled') else
if (!ini_get("date.timezone"))
Function Documentation
eZUpdateDebugSettings ()
Reads settings from site.ini and passes them to eZDebug.
Definition at line 39 of file webservicescontroller.php.
eZUpdateTextCodecSettings ()
Reads settings from i18n.ini and passes them to eZTextCodec.
Definition at line 95 of file webservicescontroller.php.
Variable Documentation
$access = changeAccess($access)
Definition at line 79 of file webservicescontroller.php.
$enable = $wsINI->variable('GeneralSettings', 'Enable' . strtoupper(WS_PROTOCOL))
Definition at line 118 of file webservicescontroller.php.
$GLOBALS['eZRequestedURI'] = $uri
Definition at line 53 of file webservicescontroller.php.
$ini = eZINI::instance()
Definition at line 48 of file webservicescontroller.php.
$moduleRepositories = eZModule::activeModuleRepositories()
Definition at line 114 of file webservicescontroller.php.
$uri = eZURI::instance(eZSys::requestURI())
Definition at line 52 of file webservicescontroller.php.
Referenced by ggWebservicesClient\payload(), ggRESTRequest\requestURI(), ggeZJSCoreRequest\requestURI(), ggWebservicesRequest\requestURI(), and xmlrpc_client\sendPayloadHTTP10().
$wsINI = eZINI::instance(ggeZWebservices::configFileByProtocol(WS_PROTOCOL))
Definition at line 66 of file webservicescontroller.php.
if ($wsINI->variable('GeneralSettings', 'UseDefaultAccess')=== 'enabled') else
Initial value:
{
    $access = accessType( $uri,
                          eZSys::hostname(),
                          eZSys::serverPort(),
                          eZSys::indexFile() )
Definition at line 73 of file webservicescontroller.php.
if(!ini_get("date.timezone"))
Definition at line 29 of file webservicescontroller.php.