ggwebservices: lib/xmlrpc/xmlrpcs.inc.php File Reference
xmlrpcs.inc.php File Reference
Classes
class xmlrpc_server
Functions
_xmlrpcs_errorHandler ($errcode, $errstring, $filename=null, $lineno=null, $context=null)
Error handler used to track errors that occur during server-side execution of PHP code.
_xmlrpcs_getCapabilities ($server, $m=null)
_xmlrpcs_listMethods ($server, $m=null)
_xmlrpcs_methodHelp ($server, $m)
_xmlrpcs_methodSignature ($server, $m)
_xmlrpcs_multicall ($server, $m)
_xmlrpcs_multicall_do_call ($server, $call)
_xmlrpcs_multicall_do_call_phpvals ($server, $call)
_xmlrpcs_multicall_error ($err)
xmlrpc_debugmsg ($m)
Add a string to the debug info that can be later seralized by the server as part of the response message.
Variables
$_xmlrpcs_getCapabilities_doc ='This method lists all the capabilites that the XML-RPC server has: the (more or less standard) extensions to the xmlrpc spec that it adheres to'
$_xmlrpcs_getCapabilities_sdoc =array(array('list of capabilities, described as structs with a version number and url for the spec'))
$_xmlrpcs_getCapabilities_sig =array(array($GLOBALS['xmlrpcStruct']))
$_xmlrpcs_listMethods_doc ='This method lists all the methods that the XML-RPC server knows how to dispatch'
$_xmlrpcs_listMethods_sdoc =array(array('list of method names'))
$_xmlrpcs_listMethods_sig =array(array($GLOBALS['xmlrpcArray']))
$_xmlrpcs_methodHelp_doc ='Returns help text if defined for the method passed, otherwise returns an empty string'
$_xmlrpcs_methodHelp_sdoc =array(array('method description', 'name of the method to be described'))
$_xmlrpcs_methodHelp_sig =array(array($GLOBALS['xmlrpcString'], $GLOBALS['xmlrpcString']))
$_xmlrpcs_methodSignature_doc ='Returns an array of known signatures (an array of arrays) for the method name passed. If no signatures are known, returns a none-array (test for type != array to detect missing signature)'
$_xmlrpcs_methodSignature_sdoc =array(array('list of known signatures, each sig being an array of xmlrpc type names', 'name of method to be described'))
$_xmlrpcs_methodSignature_sig =array(array($GLOBALS['xmlrpcArray'], $GLOBALS['xmlrpcString']))
$_xmlrpcs_multicall_doc = 'Boxcar multiple RPC calls in one request. See http://www.xmlrpc.com/discuss/msgReader$1208 for details'
$_xmlrpcs_multicall_sdoc = array(array('list of response structs, where each struct has the usual members', 'list of calls, with each call being represented as a struct, with members "methodname" and "params"'))
$_xmlrpcs_multicall_sig = array(array($GLOBALS['xmlrpcArray'], $GLOBALS['xmlrpcArray']))
$GLOBALS ['xmlrpcs_capabilities']
$GLOBALS ['_xmlrpcs_dmap']
$GLOBALS ['_xmlrpcs_occurred_errors'] = ''
$GLOBALS ['_xmlrpcs_prev_ehandler'] = ''
$GLOBALS ['_xmlrpc_debuginfo'] =''
Function Documentation
_xmlrpcs_errorHandler ($errcode, $errstring, $filename = null, $lineno = null, $context = null)
Error handler used to track errors that occur during server-side execution of PHP code.
This allows to report back to the client whether an internal error has occurred or not using an xmlrpc response object, instead of letting the client deal with the html junk that a PHP execution error on the server generally entails.
NB: in fact a user defined error handler can only handle WARNING, NOTICE and USER_* errors.
Definition at line 378 of file xmlrpcs.inc.php.
_xmlrpcs_getCapabilities ($server, $m = null)
Definition at line 64 of file xmlrpcs.inc.php.
_xmlrpcs_listMethods ($server, $m = null)
Definition at line 82 of file xmlrpcs.inc.php.
_xmlrpcs_methodHelp ($server, $m)
Definition at line 156 of file xmlrpcs.inc.php.
_xmlrpcs_methodSignature ($server, $m)
Definition at line 103 of file xmlrpcs.inc.php.
_xmlrpcs_multicall ($server, $m)
Definition at line 312 of file xmlrpcs.inc.php.
_xmlrpcs_multicall_do_call ($server, $call)
Definition at line 215 of file xmlrpcs.inc.php.
Referenced by _xmlrpcs_multicall().
_xmlrpcs_multicall_do_call_phpvals ($server, $call)
Definition at line 268 of file xmlrpcs.inc.php.
Referenced by _xmlrpcs_multicall().
_xmlrpcs_multicall_error ($err)
Definition at line 197 of file xmlrpcs.inc.php.
Referenced by _xmlrpcs_multicall_do_call(), and _xmlrpcs_multicall_do_call_phpvals().
xmlrpc_debugmsg ($m)
Add a string to the debug info that can be later seralized by the server as part of the response message.
Note that for best compatbility, the debug string should be encoded using the $GLOBALS['xmlrpc_internalencoding'] character set.
Parameters
string $m public
Definition at line 429 of file xmlrpcs.inc.php.
Variable Documentation
$_xmlrpcs_getCapabilities_doc ='This method lists all the capabilites that the XML-RPC server has: the (more or less standard) extensions to the xmlrpc spec that it adheres to'
Definition at line 62 of file xmlrpcs.inc.php.
$_xmlrpcs_getCapabilities_sdoc =array(array('list of capabilities, described as structs with a version number and url for the spec'))
Definition at line 63 of file xmlrpcs.inc.php.
$_xmlrpcs_getCapabilities_sig =array(array($GLOBALS['xmlrpcStruct']))
Definition at line 61 of file xmlrpcs.inc.php.
$_xmlrpcs_listMethods_doc ='This method lists all the methods that the XML-RPC server knows how to dispatch'
Definition at line 80 of file xmlrpcs.inc.php.
$_xmlrpcs_listMethods_sdoc =array(array('list of method names'))
Definition at line 81 of file xmlrpcs.inc.php.
$_xmlrpcs_listMethods_sig =array(array($GLOBALS['xmlrpcArray']))
Definition at line 79 of file xmlrpcs.inc.php.
$_xmlrpcs_methodHelp_doc ='Returns help text if defined for the method passed, otherwise returns an empty string'
Definition at line 154 of file xmlrpcs.inc.php.
$_xmlrpcs_methodHelp_sdoc =array(array('method description', 'name of the method to be described'))
Definition at line 155 of file xmlrpcs.inc.php.
$_xmlrpcs_methodHelp_sig =array(array($GLOBALS['xmlrpcString'], $GLOBALS['xmlrpcString']))
Definition at line 153 of file xmlrpcs.inc.php.
$_xmlrpcs_methodSignature_doc ='Returns an array of known signatures (an array of arrays) for the method name passed. If no signatures are known, returns a none-array (test for type != array to detect missing signature)'
Definition at line 101 of file xmlrpcs.inc.php.
$_xmlrpcs_methodSignature_sdoc =array(array('list of known signatures, each sig being an array of xmlrpc type names', 'name of method to be described'))
Definition at line 102 of file xmlrpcs.inc.php.
$_xmlrpcs_methodSignature_sig =array(array($GLOBALS['xmlrpcArray'], $GLOBALS['xmlrpcString']))
Definition at line 100 of file xmlrpcs.inc.php.
$_xmlrpcs_multicall_doc = 'Boxcar multiple RPC calls in one request. See http://www.xmlrpc.com/discuss/msgReader$1208 for details'
Definition at line 195 of file xmlrpcs.inc.php.
$_xmlrpcs_multicall_sdoc = array(array('list of response structs, where each struct has the usual members', 'list of calls, with each call being represented as a struct, with members "methodname" and "params"'))
Definition at line 196 of file xmlrpcs.inc.php.
$_xmlrpcs_multicall_sig = array(array($GLOBALS['xmlrpcArray'], $GLOBALS['xmlrpcArray']))
Definition at line 194 of file xmlrpcs.inc.php.
$GLOBALS['xmlrpcs_capabilities']
Initial value:
= array(
        'xmlrpc' => new xmlrpcval(array(
            'specUrl' => new xmlrpcval('http://www.xmlrpc.com/spec', 'string'),
            'specVersion' => new xmlrpcval(1, 'int')
        ), 'struct'),
        'system.multicall' => new xmlrpcval(array(
            'specUrl' => new xmlrpcval('http://www.xmlrpc.com/discuss/msgReader$1208', 'string'),
            'specVersion' => new xmlrpcval(1, 'int')
        ), 'struct'),
        'introspection' => new xmlrpcval(array(
            'specUrl' => new xmlrpcval('http://phpxmlrpc.sourceforge.net/doc-2/ch10.html', 'string'),
            'specVersion' => new xmlrpcval(2, 'int')
        ), 'struct')
    )
Definition at line 41 of file xmlrpcs.inc.php.
$GLOBALS['_xmlrpcs_dmap']
Initial value:
=array(
        'system.listMethods' => array(
            'function' => '_xmlrpcs_listMethods',
            'signature' => $_xmlrpcs_listMethods_sig,
            'docstring' => $_xmlrpcs_listMethods_doc,
            'signature_docs' => $_xmlrpcs_listMethods_sdoc),
        'system.methodHelp' => array(
            'function' => '_xmlrpcs_methodHelp',
            'signature' => $_xmlrpcs_methodHelp_sig,
            'docstring' => $_xmlrpcs_methodHelp_doc,
            'signature_docs' => $_xmlrpcs_methodHelp_sdoc),
        'system.methodSignature' => array(
            'function' => '_xmlrpcs_methodSignature',
            'signature' => $_xmlrpcs_methodSignature_sig,
            'docstring' => $_xmlrpcs_methodSignature_doc,
            'signature_docs' => $_xmlrpcs_methodSignature_sdoc),
        'system.multicall' => array(
            'function' => '_xmlrpcs_multicall',
            'signature' => $_xmlrpcs_multicall_sig,
            'docstring' => $_xmlrpcs_multicall_doc,
            'signature_docs' => $_xmlrpcs_multicall_sdoc),
        'system.getCapabilities' => array(
            'function' => '_xmlrpcs_getCapabilities',
            'signature' => $_xmlrpcs_getCapabilities_sig,
            'docstring' => $_xmlrpcs_getCapabilities_doc,
            'signature_docs' => $_xmlrpcs_getCapabilities_sdoc)
    )
Definition at line 338 of file xmlrpcs.inc.php.
$GLOBALS['_xmlrpcs_occurred_errors'] = ''
Definition at line 366 of file xmlrpcs.inc.php.
$GLOBALS['_xmlrpcs_prev_ehandler'] = ''
Definition at line 367 of file xmlrpcs.inc.php.
$GLOBALS['_xmlrpc_debuginfo'] =''
Definition at line 419 of file xmlrpcs.inc.php.