ggwebservices: lib/xmlrpc/xmlrpc.inc.php File Reference
xmlrpc.inc.php File Reference
Classes
class xmlrpc_client
class xmlrpcmsg
class xmlrpcresp
class xmlrpcval
Functions
decode_chunked ($buffer)
decode a string that is encoded w/ "chunked" transfer encoding as defined in rfc2068 par.
guess_encoding ($httpheader='', $xmlchunk='', $encoding_prefs=null)
xml charset encoding guessing helper function.
is_valid_charset ($encoding, $validlist)
Checks if a given charset encoding is present in a list of encodings or if it is a valid subset of any encoding in the list.
iso8601_decode ($idate, $utc=0)
Given an ISO8601 date string, return a timet in the localtime, or UTC.
iso8601_encode ($timet, $utc=0)
Given a timestamp, return the corresponding ISO8601 encoded string.
php_xmlrpc_decode ($xmlrpc_val, $options=array())
Takes an xmlrpc value in PHP xmlrpcval object format and translates it into native PHP types.
php_xmlrpc_decode_xml ($xml_val, $options=array())
Convert the xml representation of a method response, method request or single xmlrpc value into the appropriate object (a.k.a.
php_xmlrpc_encode ($php_val, $options=array())
Takes native php types and encodes them into xmlrpc PHP object format.
xmlrpc_cd ($parser, $data)
xml parser handler function for character data
xmlrpc_dh ($parser, $data)
xml parser handler function for 'other stuff', ie.
xmlrpc_ee ($parser, $name, $rebuild_xmlrpcvals=true)
xml parser handler function for close element tags
xmlrpc_ee_fast ($parser, $name)
Used in decoding xmlrpc requests/responses without rebuilding xmlrpc values.
xmlrpc_encode_entitites ($data, $src_encoding='', $dest_encoding='')
Convert a string to the correct XML representation in a target charset To help correct communication of non-ascii chars inside strings, regardless of the charset used when sending requests, parsing them, sending responses and parsing responses, an option is to convert all non-ascii chars present in the message into their equivalent 'charset entity'.
xmlrpc_se ($parser, $name, $attrs, $accept_single_vals=false)
xml parser handler function for opening element tags
xmlrpc_se_any ($parser, $name, $attrs)
Used in decoding xml chunks that might represent single xmlrpc values.
Variables
if(!function_exists('xml_parser_create')) $GLOBALS ['xmlrpcI4'] ='i4'
$GLOBALS ['xmlrpcInt'] ='int'
$GLOBALS ['xmlrpcBoolean'] ='boolean'
$GLOBALS ['xmlrpcDouble'] ='double'
$GLOBALS ['xmlrpcString'] ='string'
$GLOBALS ['xmlrpcDateTime'] ='dateTime.iso8601'
$GLOBALS ['xmlrpcBase64'] ='base64'
$GLOBALS ['xmlrpcArray'] ='array'
$GLOBALS ['xmlrpcStruct'] ='struct'
$GLOBALS ['xmlrpcValue'] ='undefined'
$GLOBALS ['xmlrpcTypes']
$GLOBALS ['xmlrpc_valid_parents']
$GLOBALS ['xmlrpcNull'] ='null'
$GLOBALS ['xmlrpcTypes']['null'] =1
$GLOBALS ['xmlEntities']
$GLOBALS ['xml_iso88591_Entities'] =array()
$GLOBALS ['xml_iso88591_Entities']['in'] = array()
$GLOBALS ['xml_iso88591_Entities']['out'] = array()
for($i=0;$i< 32;$i++) for($i=160;$i
< 256;$i++) $GLOBALS ['xmlrpcerr']
$GLOBALS ['xmlrpcstr']
$GLOBALS ['xmlrpc_defencoding'] ='UTF-8'
$GLOBALS ['xmlrpc_internalencoding'] ='ISO-8859-1'
$GLOBALS ['xmlrpcName'] ='XML-RPC for PHP'
$GLOBALS ['xmlrpcVersion'] ='3.0.0.beta'
$GLOBALS ['xmlrpcerruser'] =800
$GLOBALS ['xmlrpcerrxml'] =100
$GLOBALS ['xmlrpc_backslash'] =chr(92).chr(92)
$GLOBALS ['xmlrpc_null_extension'] =false
$GLOBALS ['xmlrpc_null_apache_encoding'] =false
$GLOBALS ['_xh'] =null
if(function_exists('xmlrpc_decode')) else
Function Documentation
decode_chunked ($buffer)
decode a string that is encoded w/ "chunked" transfer encoding as defined in rfc2068 par.
19.4.6 code shamelessly stolen from nusoap library by Dietrich Ayala
Parameters
string $buffer the string to be decoded
Returns
string
Definition at line 3625 of file xmlrpc.inc.php.
Referenced by ggWebservicesClient\parseHTTPResponse(), and xmlrpcmsg\parseResponseHeaders().
guess_encoding ($httpheader = '', $xmlchunk = '', $encoding_prefs = null)
xml charset encoding guessing helper function.
Tries to determine the charset encoding of an XML chunk received over HTTP. NB: according to the spec (RFC 3023), if text/xml content-type is received over HTTP without a content-type, we SHOULD assume it is strictly US-ASCII. But we try to be more tolerant of unconforming (legacy?) clients/servers, which will be most probably using UTF-8 anyway...
Parameters
string $httpheaders the http Content-type header
string $xmlchunk xml content buffer
string $encoding_prefs comma separated list of character encodings to be used as default (when mb extension is enabled)
Todo:
explore usage of mb_http_input(): does it detect http headers + post data? if so, use it instead of hand-detection!!!
Todo:
this test will pass if ANY header has charset specification, not only Content-Type. Fix it?
Todo:
implement check as described above?
Todo:
implement check for first bytes of string even without a BOM? (It sure looks harder than for cases WITH a BOM)
Definition at line 3685 of file xmlrpc.inc.php.
Referenced by xmlrpc_server\parseRequestHeaders(), and xmlrpcmsg\parseResponse().
is_valid_charset ($encoding, $validlist)
Checks if a given charset encoding is present in a list of encodings or if it is a valid subset of any encoding in the list.
Parameters
string $encoding charset to be tested
mixed $validlist comma separated list of valid charsets (or array of charsets)
Definition at line 3775 of file xmlrpc.inc.php.
iso8601_decode ($idate, $utc = 0)
Given an ISO8601 date string, return a timet in the localtime, or UTC.
Parameters
string $idate
int $utc either 0 or 1
Returns
int (datetime)
Definition at line 3271 of file xmlrpc.inc.php.
Referenced by php_xmlrpc_decode().
iso8601_encode ($timet, $utc = 0)
Given a timestamp, return the corresponding ISO8601 encoded string.
Really, timezones ought to be supported but the XML-RPC spec says:
"Don't assume a timezone. It should be specified by the server in its documentation what assumptions it makes about timezones."
These routines always assume localtime unless $utc is set to 1, in which case UTC is assumed and an adjustment for locale is made when encoding
Parameters
int $timet (timestamp)
int $utc (0 or 1)
Returns
string
Definition at line 3243 of file xmlrpc.inc.php.
php_xmlrpc_decode ($xmlrpc_val, $options = array())
Takes an xmlrpc value in PHP xmlrpcval object format and translates it into native PHP types.
Works with xmlrpc message objects as input, too.
Given proper options parameter, can rebuild generic php object instances (provided those have been encoded to xmlrpc format using a corresponding option in php_xmlrpc_encode()) PLEASE NOTE that rebuilding php objects involves calling their constructor function. This means that the remote communication end can decide which php code will get executed on your server, leaving the door possibly open to 'php-injection' style of attacks (provided you have some classes defined on your server that might wreak havoc if instances are built outside an appropriate context). Make sure you trust the remote server/client before eanbling this!
Author
Dan Libby (dan@l.nosp@m.ibby.nosp@m..com)
Parameters
xmlrpcval $xmlrpc_val
array $options if 'decode_php_objs' is set in the options array, xmlrpc structs can be decoded into php objects; if 'dates_as_objects' is set xmlrpc datetimes are decoded as php DateTime objects (standard is
Returns
mixed
Todo:
should we raise a warning for class not found?
Definition at line 3309 of file xmlrpc.inc.php.
php_xmlrpc_decode_xml ($xml_val, $options = array())
Convert the xml representation of a method response, method request or single xmlrpc value into the appropriate object (a.k.a.
deserialize)
Parameters
string $xml_val
array $options
Returns
mixed false on error, or an instance of either xmlrpcval, xmlrpcmsg or xmlrpcresp
Todo:
'guestimate' encoding
Definition at line 3545 of file xmlrpc.inc.php.
php_xmlrpc_encode ($php_val, $options = array())
Takes native php types and encodes them into xmlrpc PHP object format.
It will not re-encode xmlrpcval objects.
Feature creep – could support more types via optional type argument (string => datetime support has been added, ??? => base64 not yet)
If given a proper options parameter, php object instances will be encoded into 'special' xmlrpc values, that can later be decoded into php objects by calling php_xmlrpc_decode() with a corresponding option
Author
Dan Libby (dan@l.nosp@m.ibby.nosp@m..com)
Parameters
mixed $php_val the value to be converted into an xmlrpcval object
array $options can include 'encode_php_objs', 'auto_dates', 'null_extension' or 'extension_api'
Returns
xmlrpcval
Definition at line 3428 of file xmlrpc.inc.php.
Referenced by jsonrpc_server\execute(), and xmlrpc_server\execute().
xmlrpc_cd ($parser, $data)
xml parser handler function for character data
Definition at line 758 of file xmlrpc.inc.php.
xmlrpc_dh ($parser, $data)
xml parser handler function for 'other stuff', ie.
not char data or element start/end tag. In fact it only gets called on unknown entities...
Definition at line 786 of file xmlrpc.inc.php.
xmlrpc_ee ($parser, $name, $rebuild_xmlrpcvals = true)
xml parser handler function for close element tags
Todo:
this needs to treat correctly php-serialized objects, since std deserializing is done by php_xmlrpc_decode, which we will not be calling...
Todo:
: optimization creep - remove the if/elseif cycle below since the case() in which we are already did that
Todo:
check for failure of base64 decoding / catch warnings
Todo:
: find a better way of throwing an error than this!
Todo:
find a better way of throwing an error than this!
Definition at line 543 of file xmlrpc.inc.php.
Referenced by xmlrpc_ee_fast().
xmlrpc_ee_fast ($parser, $name)
Used in decoding xmlrpc requests/responses without rebuilding xmlrpc values.
Definition at line 752 of file xmlrpc.inc.php.
xmlrpc_encode_entitites ($data, $src_encoding = '', $dest_encoding = '')
Convert a string to the correct XML representation in a target charset To help correct communication of non-ascii chars inside strings, regardless of the charset used when sending requests, parsing them, sending responses and parsing responses, an option is to convert all non-ascii chars present in the message into their equivalent 'charset entity'.
Charset entities enumerated this way are independent of the charset encoding used to transmit them, and all XML parsers are bound to understand them. Note that in the std case we are not sending a charset encoding mime type along with http headers, so we are bound by RFC 3023 to emit strict us-ascii.
Todo:
do a bit of basic benchmarking (strtr vs. str_replace)
make usage of iconv() or recode_string() or mb_string() where available
Todo:
shall we replace this with a (supposedly) faster str_replace?
Definition at line 257 of file xmlrpc.inc.php.
Referenced by xmlrpcval\serializedata(), and xmlrpc_server\serializeDebug().
xmlrpc_se ($parser, $name, $attrs, $accept_single_vals = false)
xml parser handler function for opening element tags
Todo:
optimization creep: save this check into a bool variable, instead of using count() every time: there is only a single top level element in xml anyway
Todo:
we could check for 2 VALUE elements inside a MEMBER or PARAM element
Todo:
we could check for 2 NAME elements inside a MEMBER element
INVALID ELEMENT: RAISE ISF so that it is later recognized!!!
Todo:
optimization creep: move this inside the big switch() above
Definition at line 389 of file xmlrpc.inc.php.
Referenced by xmlrpc_se_any().
xmlrpc_se_any ($parser, $name, $attrs)
Used in decoding xml chunks that might represent single xmlrpc values.
Definition at line 537 of file xmlrpc.inc.php.
Variable Documentation
if (!function_exists('xml_parser_create')) $GLOBALS['xmlrpcI4'] ='i4'
Definition at line 51 of file xmlrpc.inc.php.
$GLOBALS['xmlrpcInt'] ='int'
Definition at line 52 of file xmlrpc.inc.php.
$GLOBALS['xmlrpcBoolean'] ='boolean'
Definition at line 53 of file xmlrpc.inc.php.
$GLOBALS['xmlrpcDouble'] ='double'
Definition at line 54 of file xmlrpc.inc.php.
$GLOBALS['xmlrpcString'] ='string'
Definition at line 55 of file xmlrpc.inc.php.
$GLOBALS['xmlrpcDateTime'] ='dateTime.iso8601'
Definition at line 56 of file xmlrpc.inc.php.
$GLOBALS['xmlrpcBase64'] ='base64'
Definition at line 57 of file xmlrpc.inc.php.
$GLOBALS['xmlrpcArray'] ='array'
Definition at line 58 of file xmlrpc.inc.php.
$GLOBALS['xmlrpcStruct'] ='struct'
Definition at line 59 of file xmlrpc.inc.php.
$GLOBALS['xmlrpcValue'] ='undefined'
Definition at line 60 of file xmlrpc.inc.php.
$GLOBALS['xmlrpcTypes']
Initial value:
=array(
        $GLOBALS['xmlrpcI4']       => 1,
        $GLOBALS['xmlrpcInt']      => 1,
        $GLOBALS['xmlrpcBoolean']  => 1,
        $GLOBALS['xmlrpcString']   => 1,
        $GLOBALS['xmlrpcDouble']   => 1,
        $GLOBALS['xmlrpcDateTime'] => 1,
        $GLOBALS['xmlrpcBase64']   => 1,
        $GLOBALS['xmlrpcArray']    => 2,
        $GLOBALS['xmlrpcStruct']   => 3
    )
Definition at line 62 of file xmlrpc.inc.php.
$GLOBALS['xmlrpc_valid_parents']
Initial value:
= array(
        'VALUE' => array('MEMBER', 'DATA', 'PARAM', 'FAULT'),
        'BOOLEAN' => array('VALUE'),
        'I4' => array('VALUE'),
        'INT' => array('VALUE'),
        'STRING' => array('VALUE'),
        'DOUBLE' => array('VALUE'),
        'DATETIME.ISO8601' => array('VALUE'),
        'BASE64' => array('VALUE'),
        'MEMBER' => array('STRUCT'),
        'NAME' => array('MEMBER'),
        'DATA' => array('ARRAY'),
        'ARRAY' => array('VALUE'),
        'STRUCT' => array('VALUE'),
        'PARAM' => array('PARAMS'),
        'METHODNAME' => array('METHODCALL'),
        'PARAMS' => array('METHODCALL', 'METHODRESPONSE'),
        'FAULT' => array('METHODRESPONSE'),
        'NIL' => array('VALUE'),
        'EX:NIL' => array('VALUE')
    )
Definition at line 74 of file xmlrpc.inc.php.
$GLOBALS['xmlrpcNull'] ='null'
Definition at line 97 of file xmlrpc.inc.php.
$GLOBALS['xmlrpcTypes']['null'] =1
Definition at line 98 of file xmlrpc.inc.php.
$GLOBALS['xmlEntities']
Initial value:
=array(
        'amp'  => '&',
        'quot' => '"',
        'lt'   => '<',
        'gt'   => '>',
        'apos' => "'"
    )
Deprecated:
Definition at line 102 of file xmlrpc.inc.php.
$GLOBALS['xml_iso88591_Entities'] =array()
Definition at line 112 of file xmlrpc.inc.php.
$GLOBALS['xml_iso88591_Entities']['in'] = array()
Definition at line 113 of file xmlrpc.inc.php.
$GLOBALS['xml_iso88591_Entities']['out'] = array()
Definition at line 114 of file xmlrpc.inc.php.
for ($i=0;$i< 32;$i++) for ($i=160;$i< 256;$i++) $GLOBALS['xmlrpcerr']
Initial value:
= array(
    'unknown_method'=>1,
    'invalid_return'=>2,
    'incorrect_params'=>3,
    'introspect_unknown'=>4,
    'http_error'=>5,
    'no_data'=>6,
    'no_ssl'=>7,
    'curl_fail'=>8,
    'invalid_request'=>15,
    'no_curl'=>16,
    'server_error'=>17,
    'multicall_error'=>18,
    'multicall_notstruct'=>9,
    'multicall_nomethod'=>10,
    'multicall_notstring'=>11,
    'multicall_recursion'=>12,
    'multicall_noparams'=>13,
    'multicall_notarray'=>14,
    'cannot_decompress'=>103,
    'decompress_fail'=>104,
    'dechunk_fail'=>105,
    'server_cannot_decompress'=>106,
    'server_decompress_fail'=>107
    )
Todo:
add to iso table the characters from cp_1252 range, i.e. 128 to 159? These will NOT be present in true ISO-8859-1, but will save the unwary windows user from sending junk (though no luck when reciving them...)
Definition at line 147 of file xmlrpc.inc.php.
$GLOBALS['xmlrpcstr']
Initial value:
= array(
    'unknown_method'=>'Unknown method',
    'invalid_return'=>'Invalid return payload: enable debugging to examine incoming payload',
    'incorrect_params'=>'Incorrect parameters passed to method',
    'introspect_unknown'=>"Can't introspect: method unknown",
    'http_error'=>"Didn't receive 200 OK from remote server.",
    'no_data'=>'No data received from server.',
    'no_ssl'=>'No SSL support compiled in.',
    'curl_fail'=>'CURL error',
    'invalid_request'=>'Invalid request payload',
    'no_curl'=>'No CURL support compiled in.',
    'server_error'=>'Internal server error',
    'multicall_error'=>'Received from server invalid multicall response',
    'multicall_notstruct'=>'system.multicall expected struct',
    'multicall_nomethod'=>'missing methodName',
    'multicall_notstring'=>'methodName is not a string',
    'multicall_recursion'=>'recursive system.multicall forbidden',
    'multicall_noparams'=>'missing params',
    'multicall_notarray'=>'params is not an array',
    'cannot_decompress'=>'Received from server compressed HTTP and cannot decompress',
    'decompress_fail'=>'Received from server invalid compressed HTTP',
    'dechunk_fail'=>'Received from server invalid chunked HTTP',
    'server_cannot_decompress'=>'Received from client compressed HTTP request and cannot decompress',
    'server_decompress_fail'=>'Received from client invalid compressed HTTP request'
    )
Definition at line 174 of file xmlrpc.inc.php.
$GLOBALS['xmlrpc_defencoding'] ='UTF-8'
Definition at line 204 of file xmlrpc.inc.php.
$GLOBALS['xmlrpc_internalencoding'] ='ISO-8859-1'
Definition at line 209 of file xmlrpc.inc.php.
$GLOBALS['xmlrpcName'] ='XML-RPC for PHP'
Definition at line 211 of file xmlrpc.inc.php.
$GLOBALS['xmlrpcVersion'] ='3.0.0.beta'
Definition at line 212 of file xmlrpc.inc.php.
$GLOBALS['xmlrpcerruser'] =800
Definition at line 215 of file xmlrpc.inc.php.
$GLOBALS['xmlrpcerrxml'] =100
Definition at line 217 of file xmlrpc.inc.php.
$GLOBALS['xmlrpc_backslash'] =chr(92).chr(92)
Deprecated:
Definition at line 222 of file xmlrpc.inc.php.
$GLOBALS['xmlrpc_null_extension'] =false
Definition at line 225 of file xmlrpc.inc.php.
$GLOBALS['xmlrpc_null_apache_encoding'] =false
Definition at line 228 of file xmlrpc.inc.php.
$GLOBALS['_xh'] =null
Definition at line 241 of file xmlrpc.inc.php.
if (function_exists('xmlrpc_decode')) else
Initial value:
{
        define('XMLRPC_EPI_ENABLED','0')
Definition at line 3407 of file xmlrpc.inc.php.