{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{if is_unset( $disabled ) }
    {def $disabled=false()}
{/if}
{if $disabled}
<input class="btn btn-lg button-disabled" disabled="disabled" type="submit" name="{$id_name}" value="{$value}" />
{else}
<input class="btn btn-lg btn-default" type="submit" name="{$id_name}" value="{$value}" />
{/if}
{undef $disabled}