{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{if is_unset( $disabled ) }
    {def $disabled=false()}
{/if}
{if $disabled}
<input class="tr_delay_hover r_corners button_type_15 bg_dark_color bg_cs_hover color_light" disabled="disabled" type="submit" name="{$id_name}" value="{$value}" />
{else}
<input class="tr_delay_hover r_corners button_type_15 bg_dark_color bg_cs_hover color_light" type="submit" name="{$id_name}" value="{$value}" />
{/if}
{undef $disabled}
