{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default page_uri_suffix=false()
         left_max=3
         right_max=3}
{default name=ViewParameter
         page_uri_suffix=false()
         left_max=$left_max
         right_max=$right_max}

{let page_count=int( ceil( div( $item_count,$item_limit ) ) )
      current_page=min($:page_count,
                       int( ceil( div( first_set( $view_parameters.offset, 0),
                                       $item_limit ) ) ) )
      item_previous=sub( mul( $:current_page, $item_limit ),
                         $item_limit )
      item_next=sum( mul( $:current_page, $item_limit ),
                     $item_limit )

      left_length=min($ViewParameter:current_page,$:left_max)
      right_length=max(min(sub($ViewParameter:page_count,$ViewParameter:current_page,1),$:right_max),0)
      view_parameter_text=""
      offset_text=eq( ezini( 'ControlSettings', 'AllowUserVariables', 'template.ini' ), 'true' )|choose( '/offset/', '/(offset)/' )}
{* Create view parameter text with the exception of offset *}
{section loop=$view_parameters}
 {section-exclude match=$:key|eq('offset')}
 {section-exclude match=$:item|eq('')}
 {set view_parameter_text=concat($:view_parameter_text,'/(',$:key,')/',$:item)}
{/section}



<div class="row clearfix m_bottom_15">

    <div class="col-lg-7 col-md-7 col-sm-8 col-xs-12 m_xs_bottom_10">
        {*
        <p class="d_inline_middle f_size_medium d_xs_block m_xs_bottom_5">Risultati 1 - 5 di 45</p>
        <p class="d_inline_middle f_size_medium m_left_20 m_xs_left_0">Visualizza:</p>
        <!--show items per page select-->
        <div class="custom_select f_size_medium relative d_inline_middle m_left_5">
            <div class="select_title r_corners relative color_dark" style="min-width: 75px;">9</div>
            <ul class="select_list d_none">
                <li class="tr_delay_hover">6</li>
                <li class="tr_delay_hover">3</li>
                <li class="tr_delay_hover">1</li>
            </ul>
            <select name="show" style="display: none;">
                <option value="Manufacture 1">6</option>
                <option value="Manufacture 2">3</option>
                <option value="Manufacture 3">1</option>
            </select>
        </div>
        <p class="d_inline_middle f_size_medium m_left_5">risultati per pagina</p>
        *}
    </div>


{section show=$:page_count|gt(1)}


<div class="col-lg-5 col-md-5 col-sm-4 col-xs-12 t_align_r t_xs_align_l">
    <!--pagination-->
    {switch match=$:item_previous|lt(0) }
    {case match=0}
        <!--<li><a href={concat($page_uri,$:item_previous|gt(0)|choose('',concat($:offset_text,$:item_previous)),$:view_parameter_text,$page_uri_suffix)|ezurl}><span class="text">&laquo;&nbsp;{"Previous"|i18n("design/admin/navigator")}</span></a></li>-->
        <a role="button" href="{concat($page_uri,$:item_previous|gt(0)|choose('',concat($:offset_text,$:item_previous)),$:view_parameter_text,$page_uri_suffix)|ezurl('no')}" class="button_type_10 color_dark d_inline_middle bg_cs_hover bg_light_color_1 t_align_c tr_delay_hover r_corners box_s_none">
            <i class="fa fa-angle-left"></i>
        </a>
    {/case}
    {case}
        <!--<li class="disabled"><span class="text disabled">&laquo;&nbsp;{"Previous"|i18n("design/admin/navigator")}</span></li>-->
        <span class="button_type_10 color_dark d_inline_middle bg_cs_hover bg_light_color_1 t_align_c tr_delay_hover r_corners box_s_none">
            <i class="fa fa-angle-left"></i>
        </span>
    {/case}
{/switch}
    <ul class="horizontal_list clearfix d_inline_middle f_size_medium m_left_10">

{if $:current_page|gt($:left_max)}
<li><a href={concat($page_uri,$:view_parameter_text,$page_uri_suffix)|ezurl}>1</a></li>
{if sub($:current_page,$:left_length)|gt(1)}
<li class="m_right_10"><a>...</a></li>
{/if}
{/if}

    {section loop=$:left_length}
        {let page_offset=sum(sub($ViewParameter:current_page,$ViewParameter:left_length),$:index)}
          <li class="m_right_10"><a class="color_dark" href={concat($page_uri,$:page_offset|gt(0)|choose('',concat($:offset_text,mul($:page_offset,$item_limit))),$ViewParameter:view_parameter_text,$page_uri_suffix)|ezurl}>{$:page_offset|inc}</a></li>
        {/let}
    {/section}

        {* Active *}
        <li class="m_right_10"><a class="scheme_color" href="#">{$:current_page|inc}</a></li>

    {section loop=$:right_length}
        {let page_offset=sum($ViewParameter:current_page,1,$:index)}
          <li class="m_right_10"><a class="color_dark" href={concat($page_uri,$:page_offset|gt(0)|choose('',concat($:offset_text,mul($:page_offset,$item_limit))),$ViewParameter:view_parameter_text,$page_uri_suffix)|ezurl}>{$:page_offset|inc}</a></li>
        {/let}
    {/section}

    {if $:page_count|gt(sum($:current_page,$:right_max,1))}
        {if sum($:current_page,$:right_max,2)|lt($:page_count)}
            <li class="m_right_10"><a>...</a></li>
        {/if}
        <li><a href={concat($page_uri,$:page_count|dec|gt(0)|choose('',concat($:offset_text,mul($:page_count|dec,$item_limit))),$:view_parameter_text,$page_uri_suffix)|ezurl}>{$:page_count}</a></li>
    {/if}

    </ul>
    {switch match=$:item_next|lt($item_count)}
        {case match=1}
            <!--<li><a href={concat($page_uri,$:offset_text,$:item_next,$:view_parameter_text,$page_uri_suffix)|ezurl}><span class="text">{"Next"|i18n("design/admin/navigator")}&nbsp;&raquo;</span></a></li>-->
            <a role="button" href="{concat($page_uri,$:offset_text,$:item_next,$:view_parameter_text,$page_uri_suffix)|ezurl('no')}" class="button_type_10 color_dark d_inline_middle bg_cs_hover bg_light_color_1 t_align_c tr_delay_hover r_corners box_s_none">
              <i class="fa fa-angle-right"></i>
            </a>
        {/case}
        {case}
            <!--<li class="disabled"><span class="text disabled">{"Next"|i18n("design/admin/navigator")}&nbsp;&raquo;</span></li>-->
            <span class="button_type_10 color_dark d_inline_middle bg_cs_hover bg_light_color_1 t_align_c tr_delay_hover r_corners box_s_none">
              <i class="fa fa-angle-right"></i>
            </span>
        {/case}
    {/switch}
</div>
{/section}

 {/let}
{/default}
{/default}

</div>
